#!/usr/bin/env node
/**
 * regression-upgrade.cjs — Auto-generated by mycelium-upgrade
 * 
 * Targeted regression tests for the top 52 failure patterns
 * found in the project's breakage history.
 * 
 * Generated: 2026-02-09
 * Source: .mycelium/watch.json (50 breakages analyzed)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');

let passed = 0, failed = 0, skipped = 0;

function assert(condition, msg) {
  if (!condition) {
    console.log('  \x1b[31m✗\x1b[0m ' + msg);
    failed++;
    throw new Error(msg);
  }
}

console.log('');
console.log('  \x1b[1mregression-upgrade\x1b[0m — 52 tests from 50 breakage patterns');
console.log('');

const results = [];


  // ── cards-i18n-keys-valid (i18n) ──
  try {
    // cards: i18n keys must not start with digits (broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'cards: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'cards-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── cards-i18n-register-call (i18n) ──
  try {
    // cards: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'cards: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'cards: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'cards: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'cards-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── cards-viewport-meta (mobile) ──
  try {
    // cards: must have viewport meta tag (mobile broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      assert(html.includes('viewport'), 'cards: missing viewport meta tag');
      passed++;
    }
    results.push({ name: 'cards-viewport-meta', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-viewport-meta', status: 'fail', error: e.message });
  }


  // ── cards-no-fixed-width (mobile) ──
  try {
    // cards: no hardcoded px widths over 400px in inline styles (mobile breakage pattern)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      const badWidths = [...html.matchAll(/style="[^"]*width:\s*(\d+)px/g)]
        .filter(m => parseInt(m[1]) > 400);
      assert(badWidths.length === 0, 'cards: hardcoded wide px widths: ' + badWidths.map(m => m[1]+'px').join(', '));
      passed++;
    }
    results.push({ name: 'cards-no-fixed-width', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-no-fixed-width', status: 'fail', error: e.message });
  }


  // ── cards-no-overflow-hidden-on-game (layout) ──
  try {
    // cards: overflow:hidden clips cards on mobile (broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      const arenaOverflow = html.match(/\.arena[^}]*overflow:\s*hidden/);
      assert(!arenaOverflow, 'cards: .arena uses overflow:hidden — clips cards on 320px');
      passed++;
    }
    results.push({ name: 'cards-no-overflow-hidden-on-game', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-no-overflow-hidden-on-game', status: 'fail', error: e.message });
  }


  // ── cards-has-testid (structure) ──
  try {
    // cards: must have data-testid markers (broke 10x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/cards.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'cards: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'cards-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'cards-has-testid', status: 'fail', error: e.message });
  }


  // ── markets-i18n-keys-valid (i18n) ──
  try {
    // markets: i18n keys must not start with digits (broke 3x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'markets: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'markets-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── markets-i18n-register-call (i18n) ──
  try {
    // markets: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'markets: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'markets: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'markets: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'markets-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── markets-viewport-meta (mobile) ──
  try {
    // markets: must have viewport meta tag (mobile broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      assert(html.includes('viewport'), 'markets: missing viewport meta tag');
      passed++;
    }
    results.push({ name: 'markets-viewport-meta', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-viewport-meta', status: 'fail', error: e.message });
  }


  // ── markets-no-fixed-width (mobile) ──
  try {
    // markets: no hardcoded px widths over 400px in inline styles (mobile breakage pattern)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      const badWidths = [...html.matchAll(/style="[^"]*width:\s*(\d+)px/g)]
        .filter(m => parseInt(m[1]) > 400);
      assert(badWidths.length === 0, 'markets: hardcoded wide px widths: ' + badWidths.map(m => m[1]+'px').join(', '));
      passed++;
    }
    results.push({ name: 'markets-no-fixed-width', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-no-fixed-width', status: 'fail', error: e.message });
  }


  // ── markets-touch-handling-flag (mobile) ──
  try {
    // markets: touchend handlers must have handling/flag guard (iOS double-fire)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      if (html.includes('touchend')) {
        const hasSafeguard = html.includes('handling') || html.includes('isHandling') || 
                             html.includes('touchActive') || html.includes('preventDefault');
        assert(hasSafeguard, 'markets: touchend without handling flag — iOS will double-fire');
      }
      passed++;
    }
    results.push({ name: 'markets-touch-handling-flag', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-touch-handling-flag', status: 'fail', error: e.message });
  }


  // ── markets-null-safe-selectors (runtime) ──
  try {
    // markets: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ markets: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'markets-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── markets-has-testid (structure) ──
  try {
    // markets: must have data-testid markers (broke 7x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/markets.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'markets: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'markets-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'markets-has-testid', status: 'fail', error: e.message });
  }


  // ── battle-viewport-meta (mobile) ──
  try {
    // battle: must have viewport meta tag (mobile broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/battle.html'), 'utf8');
      assert(html.includes('viewport'), 'battle: missing viewport meta tag');
      passed++;
    }
    results.push({ name: 'battle-viewport-meta', status: 'pass' });
  } catch (e) {
    results.push({ name: 'battle-viewport-meta', status: 'fail', error: e.message });
  }


  // ── battle-no-fixed-width (mobile) ──
  try {
    // battle: no hardcoded px widths over 400px in inline styles (mobile breakage pattern)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/battle.html'), 'utf8');
      const badWidths = [...html.matchAll(/style="[^"]*width:\s*(\d+)px/g)]
        .filter(m => parseInt(m[1]) > 400);
      assert(badWidths.length === 0, 'battle: hardcoded wide px widths: ' + badWidths.map(m => m[1]+'px').join(', '));
      passed++;
    }
    results.push({ name: 'battle-no-fixed-width', status: 'pass' });
  } catch (e) {
    results.push({ name: 'battle-no-fixed-width', status: 'fail', error: e.message });
  }


  // ── battle-no-overflow-hidden-on-game (layout) ──
  try {
    // battle: overflow:hidden clips cards on mobile (broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/battle.html'), 'utf8');
      const arenaOverflow = html.match(/\.arena[^}]*overflow:\s*hidden/);
      assert(!arenaOverflow, 'battle: .arena uses overflow:hidden — clips cards on 320px');
      passed++;
    }
    results.push({ name: 'battle-no-overflow-hidden-on-game', status: 'pass' });
  } catch (e) {
    results.push({ name: 'battle-no-overflow-hidden-on-game', status: 'fail', error: e.message });
  }


  // ── battle-has-testid (structure) ──
  try {
    // battle: must have data-testid markers (broke 7x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/battle.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'battle: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'battle-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'battle-has-testid', status: 'fail', error: e.message });
  }


  // ── wyckoff-i18n-keys-valid (i18n) ──
  try {
    // wyckoff: i18n keys must not start with digits (broke 4x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/wyckoff.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'wyckoff: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'wyckoff-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'wyckoff-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── wyckoff-i18n-register-call (i18n) ──
  try {
    // wyckoff: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/wyckoff.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'wyckoff: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'wyckoff: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'wyckoff: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'wyckoff-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'wyckoff-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── wyckoff-null-safe-selectors (runtime) ──
  try {
    // wyckoff: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/wyckoff.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ wyckoff: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'wyckoff-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'wyckoff-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── wyckoff-has-testid (structure) ──
  try {
    // wyckoff: must have data-testid markers (broke 5x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/wyckoff.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'wyckoff: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'wyckoff-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'wyckoff-has-testid', status: 'fail', error: e.message });
  }


  // ── merch-i18n-keys-valid (i18n) ──
  try {
    // merch: i18n keys must not start with digits (broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/merch.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'merch: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'merch-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'merch-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── merch-i18n-register-call (i18n) ──
  try {
    // merch: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/merch.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'merch: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'merch: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'merch: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'merch-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'merch-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── merch-no-overflow-hidden-on-game (layout) ──
  try {
    // merch: overflow:hidden clips cards on mobile (broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/merch.html'), 'utf8');
      const arenaOverflow = html.match(/\.arena[^}]*overflow:\s*hidden/);
      assert(!arenaOverflow, 'merch: .arena uses overflow:hidden — clips cards on 320px');
      passed++;
    }
    results.push({ name: 'merch-no-overflow-hidden-on-game', status: 'pass' });
  } catch (e) {
    results.push({ name: 'merch-no-overflow-hidden-on-game', status: 'fail', error: e.message });
  }


  // ── merch-null-safe-selectors (runtime) ──
  try {
    // merch: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/merch.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ merch: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'merch-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'merch-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── merch-has-testid (structure) ──
  try {
    // merch: must have data-testid markers (broke 5x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/merch.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'merch: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'merch-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'merch-has-testid', status: 'fail', error: e.message });
  }


  // ── pvp-battle-i18n-keys-valid (i18n) ──
  try {
    // pvp-battle: i18n keys must not start with digits (broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/pvp-battle.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'pvp-battle: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'pvp-battle-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'pvp-battle-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── pvp-battle-i18n-register-call (i18n) ──
  try {
    // pvp-battle: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/pvp-battle.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'pvp-battle: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'pvp-battle: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'pvp-battle: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'pvp-battle-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'pvp-battle-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── pvp-battle-null-safe-selectors (runtime) ──
  try {
    // pvp-battle: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/pvp-battle.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ pvp-battle: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'pvp-battle-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'pvp-battle-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── pvp-battle-has-testid (structure) ──
  try {
    // pvp-battle: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/pvp-battle.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'pvp-battle: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'pvp-battle-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'pvp-battle-has-testid', status: 'fail', error: e.message });
  }


  // ── embassy-i18n-keys-valid (i18n) ──
  try {
    // embassy: i18n keys must not start with digits (broke 3x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/embassy.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'embassy: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'embassy-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'embassy-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── embassy-i18n-register-call (i18n) ──
  try {
    // embassy: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/embassy.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'embassy: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'embassy: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'embassy: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'embassy-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'embassy-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── embassy-null-safe-selectors (runtime) ──
  try {
    // embassy: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/embassy.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ embassy: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'embassy-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'embassy-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── embassy-has-testid (structure) ──
  try {
    // embassy: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/embassy.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'embassy: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'embassy-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'embassy-has-testid', status: 'fail', error: e.message });
  }


  // ── profile-card-i18n-keys-valid (i18n) ──
  try {
    // profile-card: i18n keys must not start with digits (broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'profile-card: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'profile-card-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── profile-card-i18n-register-call (i18n) ──
  try {
    // profile-card: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'profile-card: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'profile-card: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'profile-card: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'profile-card-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── profile-card-viewport-meta (mobile) ──
  try {
    // profile-card: must have viewport meta tag (mobile broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      assert(html.includes('viewport'), 'profile-card: missing viewport meta tag');
      passed++;
    }
    results.push({ name: 'profile-card-viewport-meta', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-viewport-meta', status: 'fail', error: e.message });
  }


  // ── profile-card-no-fixed-width (mobile) ──
  try {
    // profile-card: no hardcoded px widths over 400px in inline styles (mobile breakage pattern)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      const badWidths = [...html.matchAll(/style="[^"]*width:\s*(\d+)px/g)]
        .filter(m => parseInt(m[1]) > 400);
      assert(badWidths.length === 0, 'profile-card: hardcoded wide px widths: ' + badWidths.map(m => m[1]+'px').join(', '));
      passed++;
    }
    results.push({ name: 'profile-card-no-fixed-width', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-no-fixed-width', status: 'fail', error: e.message });
  }


  // ── profile-card-null-safe-selectors (runtime) ──
  try {
    // profile-card: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ profile-card: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'profile-card-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── profile-card-has-testid (structure) ──
  try {
    // profile-card: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/profile-card.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'profile-card: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'profile-card-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'profile-card-has-testid', status: 'fail', error: e.message });
  }


  // ── index-i18n-keys-valid (i18n) ──
  try {
    // index: i18n keys must not start with digits (broke 1x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/index.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'index: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'index-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'index-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── index-i18n-register-call (i18n) ──
  try {
    // index: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/index.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'index: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'index: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'index: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'index-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'index-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── index-null-safe-selectors (runtime) ──
  try {
    // index: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/index.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ index: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'index-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'index-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── index-has-testid (structure) ──
  try {
    // index: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/index.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'index: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'index-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'index-has-testid', status: 'fail', error: e.message });
  }


  // ── events-i18n-keys-valid (i18n) ──
  try {
    // events: i18n keys must not start with digits (broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/events.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'events: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'events-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'events-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── events-i18n-register-call (i18n) ──
  try {
    // events: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/events.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'events: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'events: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'events: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'events-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'events-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── events-null-safe-selectors (runtime) ──
  try {
    // events: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/events.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ events: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'events-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'events-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── events-has-testid (structure) ──
  try {
    // events: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/events.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'events: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'events-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'events-has-testid', status: 'fail', error: e.message });
  }


  // ── historical-society-i18n-keys-valid (i18n) ──
  try {
    // historical-society: i18n keys must not start with digits (broke 2x)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/historical-society.html'), 'utf8');
      const keys = [...html.matchAll(/data-i18n="([^"]+)"/g)].map(m => m[1]);
      const bad = keys.filter(k => /^\d/.test(k));
      assert(bad.length === 0, 'historical-society: i18n keys starting with digit: ' + bad.join(', '));
      passed++;
    }
    results.push({ name: 'historical-society-i18n-keys-valid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'historical-society-i18n-keys-valid', status: 'fail', error: e.message });
  }


  // ── historical-society-i18n-register-call (i18n) ──
  try {
    // historical-society: must call NW_I18N.register with all 3 languages
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/historical-society.html'), 'utf8');
      if (html.includes('NW_I18N')) {
        assert(html.includes("'en'") || html.includes('"en"') || html.match(/\ben\s*:/), 'historical-society: missing EN translations');
        assert(html.includes("'zh'") || html.includes('"zh"') || html.match(/\bzh\s*:/), 'historical-society: missing ZH translations');
        assert(html.includes("'th'") || html.includes('"th"') || html.match(/\bth\s*:/), 'historical-society: missing TH translations');
      }
      passed++;
    }
    results.push({ name: 'historical-society-i18n-register-call', status: 'pass' });
  } catch (e) {
    results.push({ name: 'historical-society-i18n-register-call', status: 'fail', error: e.message });
  }


  // ── historical-society-null-safe-selectors (runtime) ──
  try {
    // historical-society: querySelectorAll results must be null-checked
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/historical-society.html'), 'utf8');
      const singleSelectors = [...html.matchAll(/querySelector\([^)]+\)\./g)];
      // querySelector().something without null check — potential crash
      const unsafe = singleSelectors.filter(m => !m[0].includes('?.'));
      // Allow up to some — the point is awareness
      if (unsafe.length > 10) {
        console.log('    ⚠ historical-society: ' + unsafe.length + ' querySelector calls without ?. null-check');
      }
      passed++;
    }
    results.push({ name: 'historical-society-null-safe-selectors', status: 'pass' });
  } catch (e) {
    results.push({ name: 'historical-society-null-safe-selectors', status: 'fail', error: e.message });
  }


  // ── historical-society-has-testid (structure) ──
  try {
    // historical-society: must have data-testid markers (broke 4x total)
    {
      const html = fs.readFileSync(path.join(ROOT, 'public/historical-society.html'), 'utf8');
      const testIds = [...html.matchAll(/data-testid="([^"]+)"/g)].map(m => m[1]);
      assert(testIds.length >= 1, 'historical-society: no data-testid markers — add at least one for regression testing');
      passed++;
    }
    results.push({ name: 'historical-society-has-testid', status: 'pass' });
  } catch (e) {
    results.push({ name: 'historical-society-has-testid', status: 'fail', error: e.message });
  }


// Summary
console.log('');
results.filter(r => r.status === 'pass').forEach(r => {
  console.log('  \x1b[32m✓\x1b[0m ' + r.name);
});
results.filter(r => r.status === 'fail').forEach(r => {
  console.log('  \x1b[31m✗\x1b[0m ' + r.name + ': ' + r.error);
});

console.log('');
console.log('  ' + passed + ' passed, ' + failed + ' failed, ' + skipped + ' skipped');
console.log('');

process.exit(failed > 0 ? 1 : 0);
