-- Mycelium Breakage Pattern Database
-- Generated: 2026-07-05T09:05:11.532Z
-- Repo: webapp
-- Schema version: 2.0

PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS repos (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  total_commits INTEGER DEFAULT 0,
  analyzed_commits INTEGER DEFAULT 0,
  first_date TEXT,
  last_date TEXT,
  mined_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS patterns (
  id TEXT PRIMARY KEY,
  repo_id TEXT NOT NULL,
  name TEXT NOT NULL,
  frequency INTEGER NOT NULL,
  category TEXT NOT NULL,
  technology TEXT,
  severity TEXT CHECK(severity IN ('low','medium','high','critical')),
  rule TEXT NOT NULL,
  root_cause TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);

CREATE TABLE IF NOT EXISTS pattern_examples (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pattern_id TEXT NOT NULL,
  commit_hash TEXT,
  commit_message TEXT,
  commit_date TEXT,
  FOREIGN KEY (pattern_id) REFERENCES patterns(id)
);

CREATE TABLE IF NOT EXISTS hotspots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repo_id TEXT NOT NULL,
  file_path TEXT NOT NULL,
  total_changes INTEGER NOT NULL,
  fix_count INTEGER NOT NULL,
  fix_rate REAL NOT NULL,
  risk_level TEXT CHECK(risk_level IN ('low','medium','high','critical')),
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);

CREATE TABLE IF NOT EXISTS coupling (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repo_id TEXT NOT NULL,
  file_a TEXT NOT NULL,
  file_b TEXT NOT NULL,
  co_change_count INTEGER NOT NULL,
  strength TEXT CHECK(strength IN ('weak','moderate','strong')),
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);

CREATE TABLE IF NOT EXISTS fix_commits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repo_id TEXT NOT NULL,
  commit_hash TEXT NOT NULL,
  commit_date TEXT,
  author TEXT,
  message TEXT,
  category TEXT,
  pattern TEXT,
  severity TEXT,
  root_cause TEXT,
  file_count INTEGER,
  confidence REAL,
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);

CREATE TABLE IF NOT EXISTS fix_chains (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repo_id TEXT NOT NULL,
  break_hash TEXT,
  break_message TEXT,
  fix_hash TEXT,
  fix_message TEXT,
  hours_to_fix REAL,
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);

CREATE INDEX IF NOT EXISTS idx_patterns_category ON patterns(category);
CREATE INDEX IF NOT EXISTS idx_patterns_severity ON patterns(severity);
CREATE INDEX IF NOT EXISTS idx_patterns_frequency ON patterns(frequency DESC);
CREATE INDEX IF NOT EXISTS idx_hotspots_fix_rate ON hotspots(fix_rate DESC);
CREATE INDEX IF NOT EXISTS idx_coupling_count ON coupling(co_change_count DESC);
CREATE INDEX IF NOT EXISTS idx_fix_commits_category ON fix_commits(category);

INSERT OR REPLACE INTO repos VALUES ('webapp', 'webapp', 731, 300, '2026-01-23', '2026-07-05', '2026-07-05T09:05:11.532Z');

INSERT OR REPLACE INTO patterns VALUES ('MCL-WRONG-CSS-VALUE', 'webapp', 'wrong-css-value', 13, 'css-layout', 'html', 'medium', 'CSS value changes should be tested at multiple screen sizes. Check for inherited properties and specificity conflicts.', 'Changed height: 120px → 100%. Also: Changed background: linear-gradient(180deg,#ffcc70 0%,#ff9500 30%,#ff6b00 60%,#cc4400 100%) → radial-gradient(ellipse at 20% 20%,rgba(255,107,0,.2) 0%,transparent 50%),radial-gradient(ellipse at 80% 80%,rgba(255,157,77,.15) 0%,transparent 50%); Changed height: 100', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-CSS-VALUE', '6cb468d1', 'fix(guild): music toggle was hidden behind the langbar — move to top-left (#102)', '2026-06-04');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-CSS-VALUE', 'e713c399', 'fix(guild): rebuild join headline with real word spans + flex gaps (#86)', '2026-06-03');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-CSS-VALUE', 'd7fbdadd', 'fix(guild): keep ROSTER whole on mobile + mobile-first headline sizing (#85)', '2026-06-03');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-CSS-VALUE', '0921c9e1', 'fix(guild): preserve word spacing in join headline + stack lines cleanly (#84)', '2026-06-03');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-CSS-VALUE', 'f3d3842a', 'feat(guild): trilingual TH/JA/EN, readability fix, dark-inside origin story (#72)', '2026-06-02');
INSERT OR REPLACE INTO patterns VALUES ('MCL-MISSING-RETURN-STATEMENT', 'webapp', 'missing-return-statement', 6, 'logic-error', 'javascript', 'high', 'Functions that compute values must return them. Missing return causes undefined results and silent failures.', 'Added missing return statement — function was returning undefined. Also: Added missing return statement — function was returning undefined', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RETURN-STATEMENT', '844a02ad', 'refactor(cli): fix ANSI-leak bug + consolidate duplicated plumbing onto the shared lib', '2026-06-19');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RETURN-STATEMENT', '55149f7f', 'fix(learning): rewire the self-improvement stack — live signals, trends→rules, auto-logged efficienc', '2026-06-04');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RETURN-STATEMENT', 'a51a9be3', 'fix(guild): remove dark island inside P + handle fused-island case in tooling (#82)', '2026-06-03');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RETURN-STATEMENT', '13d6b3b9', 'fix(guild): clean demon-P emblem + deterministic emblem pipeline & asset gate (#81)', '2026-06-03');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RETURN-STATEMENT', '69ea4620', 'fix(cinematic): rewatch button dead on returning visitors', '2026-02-14');
INSERT OR REPLACE INTO patterns VALUES ('MCL-I18N-MISSING-TRANSLATION', 'webapp', 'i18n-missing-translation', 6, 'i18n', 'html', 'medium', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed digit-starting i18n key bug in index.html. RULE: Ensure all user-visible strings go through the translation system.', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed digit-starting i18n key bug in index.html', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-I18N-MISSING-TRANSLATION', '4e6d427f', 'fix: nuke buy-toast entirely — direct redirect to /buy.html, no popup', '2026-02-11');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-I18N-MISSING-TRANSLATION', 'f71797da', 'fix(cleanup): remove Qing/卿 personalization, emoji animations, streak/achievement systems', '2026-02-11');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-I18N-MISSING-TRANSLATION', '1998cc92', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed dig', '2026-02-09');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-I18N-MISSING-TRANSLATION', '98b541bd', 'feat(sentinel): Upgrade to v2.5 — 10-module health platform with trend tracking & auto-fix engine', '2026-02-07');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-I18N-MISSING-TRANSLATION', 'a3046c00', 'Fix: use data-i18n-html for HTML content in wyckoff intro', '2026-02-05');
INSERT OR REPLACE INTO patterns VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', 'webapp', 'overflow-hidden-clips-children', 5, 'css-layout', 'html', 'high', 'overflow:hidden on a parent silently clips children that extend beyond bounds. Check all child elements before adding it.', 'Added overflow:hidden — may clip child elements. Also: Changed cards: fill width with 4px gaps, minimum 64px */
--board-card-width: clamp(64px, calc((100vw - 40px) / 5), 80px) → compact to leave room for hand */
--board-card-width: clamp(56px, calc((100vw - 40px) / 5), 72px); Changed board-card-heig', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', '8ed2bf0e', 'fix(guild): zoom out the forest backgrounds on iOS + use ALL ambience art (#93)', '2026-06-04');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', '90ee99e4', 'fix(invest): merch-card mobile overlap — title/body no longer hidden behind photo', '2026-05-01');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', '46cec269', 'fix(battle): Mobile hand cards visibility + fix Illegal return statement', '2026-02-08');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', '1c919aa6', 'fix(battle): Fix mobile hand cards not visible — arena overflow + flex layout', '2026-02-08');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-OVERFLOW-HIDDEN-CLIPS-CHILDREN', '420f4e6f', 'fix(avatar-studio): Improve mobile touch interactions', '2026-02-06');
INSERT OR REPLACE INTO patterns VALUES ('MCL-TEST-ISSUE', 'webapp', 'test-issue', 4, 'test-failure', 'config', 'high', 'make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cjs syntax errors, rename .nw-* to .mycelium-*, tested end-to-end o. RULE: Review carefully before committing.', 'make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cjs syntax errors, rename .nw-* to .mycelium-*, tested end-to-end on fresh repo', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-TEST-ISSUE', '0f389e8c', 'fix: Scene 09 v9 — DARK skin for RegginA/RegginO + accurate R.M.S. Regina', '2026-02-16');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-TEST-ISSUE', 'f965e84e', 'fix(portable): make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cj', '2026-02-09');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-TEST-ISSUE', '847fe089', 'fix(honesty): record underselling breakage + add HONESTY GATE to CLAUDE.md — never claim something d', '2026-02-09');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-TEST-ISSUE', 'adf49f14', 'fix(showcase): strip fake impact metrics (hours/money/pts saved) — replace with provable numbers onl', '2026-02-09');
INSERT OR REPLACE INTO patterns VALUES ('MCL-CSS-LAYOUT-ISSUE', 'webapp', 'css-layout-issue', 3, 'css-layout', 'html', 'medium', 'repair the silent heal loop — eval bridge, blame guard, recency-aware health. RULE: Test layout at 320px, 768px, 1024px after CSS changes.', 'repair the silent heal loop — eval bridge, blame guard, recency-aware health', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-CSS-LAYOUT-ISSUE', 'b8fb2d87', 'fix(learning): repair the silent heal loop — eval bridge, blame guard, recency-aware health', '2026-06-10');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-CSS-LAYOUT-ISSUE', '0e2c4f57', 'fix(invest/liveops): proportional ship speeds calibrated to photo geometry', '2026-05-02');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-CSS-LAYOUT-ISSUE', '5c306d2b', 'fix(invest): remove ambient audio system + all corner watermark badges', '2026-05-01');
INSERT OR REPLACE INTO patterns VALUES ('MCL-MISSING-RESPONSIVE-BREAKPOINT', 'webapp', 'missing-responsive-breakpoint', 3, 'mobile-compat', 'config', 'medium', 'Test every UI change at 320px, 768px, and 1024px. Add @media breakpoints for layouts that break at different screen sizes.', 'Stats grid was overlapping on small screens due to fixed px positions', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RESPONSIVE-BREAKPOINT', 'd6ae78eb', 'feat(system): AGENT-CONTEXT.md + full audit fixes', '2026-02-11');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RESPONSIVE-BREAKPOINT', 'f07a5776', 'fix(rebrand): add kintsugi.html landing page + update memory to v2 KINTSUGI brand', '2026-02-11');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-RESPONSIVE-BREAKPOINT', 'e231b1af', 'Fix iOS mobile overlap on Profile Card', '2026-02-04');
INSERT OR REPLACE INTO patterns VALUES ('MCL-MISSING-PRECONDITION-CHECK', 'webapp', 'missing-precondition-check', 3, 'null-reference', 'html', 'medium', 'Validate prerequisites before executing logic. Check that DOM elements exist, APIs are loaded, and data is present before using them.', 'selfHeal gated at 10 commits, but squash workflow compresses 4-5→1,', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-PRECONDITION-CHECK', '40f1d812', 'fix(showcase): NaN scores, mobile charts 2x, fonts doubled, README rewrite for Mycelium', '2026-02-09');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-PRECONDITION-CHECK', 'dd67dac1', 'fix(automation): make learning system fully automatic — no manual heal/eval needed (#13)', '2026-02-09');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-PRECONDITION-CHECK', '76de3af6', 'fix(battle): Move deck building + hand dealing to START button click', '2026-02-08');
INSERT OR REPLACE INTO patterns VALUES ('MCL-SCRIPT-ORDER-DEPENDENCY', 'webapp', 'script-order-dependency', 3, 'load-order', 'html', 'high', 'Scripts that call each other''s globals must load in dependency order. Document the dependency chain in a comment.', 'showed overlay never appears on iOS mobile — user goes straight to', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-SCRIPT-ORDER-DEPENDENCY', '3affe035', 'fix(battle): Auto-start game when overlay isn''t visible on iOS', '2026-02-08');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-SCRIPT-ORDER-DEPENDENCY', 'e25565d5', 'fix(battle): Don''t block init on Audio.init() - fixes iOS hand empty bug', '2026-02-08');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-SCRIPT-ORDER-DEPENDENCY', 'a64bf8da', 'fix(battle): Add mobile debug overlay + cache busting v5.1', '2026-02-08');
INSERT OR REPLACE INTO patterns VALUES ('MCL-BUILD-CONFIG-ISSUE', 'webapp', 'build-config-issue', 2, 'build-config', 'config', 'high', 'make TSC-0-errors claim true (142 → 0) + add reproducible credibility audit. RULE: Verify build output matches expected file structure.', 'make TSC-0-errors claim true (142 → 0) + add reproducible credibility audit', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-BUILD-CONFIG-ISSUE', '437379df', 'fix(build): make TSC-0-errors claim true (142 → 0) + add reproducible credibility audit', '2026-06-17');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-BUILD-CONFIG-ISSUE', 'b4c72a9e', 'feat(pipeline): trailer production pipeline + iOS Safari cinematic fix', '2026-02-14');
INSERT OR REPLACE INTO patterns VALUES ('MCL-WRONG-ASSET-PATH', 'webapp', 'wrong-asset-path', 2, 'build-config', 'html', 'low', 'Use path constants or import for assets. Hardcoded paths break when files move or builds change output directories.', 'Changed resource path', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-ASSET-PATH', 'c880eb90', 'revert(guild): switch page music back to the original anime OST (v1) (#105)', '2026-06-04');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-WRONG-ASSET-PATH', '101f6578', 'FIX: Optimized currency icons + market page fixes', '2026-02-04');
INSERT OR REPLACE INTO patterns VALUES ('MCL-MISSING-NULL-GUARD', 'webapp', 'missing-null-guard', 2, 'null-reference', 'html', 'medium', 'Always use optional chaining (?.) when accessing properties on objects that may be undefined, especially DOM queries and API responses.', 'Added 1 optional chaining operator(s) — null reference fix. Also: Added && guard — was executing without prerequisite check; Modified conditional logic', '2026-07-05T09:05:11.532Z');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-NULL-GUARD', 'ec3364d0', 'fix(cards): Fix language toggle not working', '2026-02-06');
INSERT INTO pattern_examples (pattern_id, commit_hash, commit_message, commit_date) VALUES ('MCL-MISSING-NULL-GUARD', 'fcb85258', 'Fix merch.html: null element error crashing product grid render', '2026-02-04');

INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/static/data/sentinel-report.json', 46, 10, 0.217, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/static/data/sentinel-history.json', 45, 10, 0.222, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/invest.html', 39, 5, 0.128, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'package.json', 37, 3, 0.081, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', '.mycelium/memory.json', 31, 9, 0.29, 'high');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/static/data/showcase-live.json', 29, 4, 0.138, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'src/index.tsx', 27, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/static/nw-nav.js', 26, 1, 0.038, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', '.gitignore', 23, 2, 0.087, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/merch.html', 21, 3, 0.143, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'CLAUDE.md', 20, 6, 0.3, 'high');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'bin/ai.cjs', 20, 2, 0.1, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/battle.html', 20, 3, 0.15, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/cards.html', 19, 5, 0.263, 'high');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'README.md', 18, 6, 0.333, 'high');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/guild/brightinside/index.html', 18, 7, 0.389, 'high');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/index.html', 18, 3, 0.167, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/wyckoff.html', 18, 1, 0.056, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/embassy.html', 16, 1, 0.063, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/events.html', 16, 2, 0.125, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/wallet.html', 16, 1, 0.063, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', '.mycelium/eval.json', 15, 7, 0.467, 'critical');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', '.husky/post-commit', 15, 3, 0.2, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', '.husky/pre-commit', 15, 2, 0.133, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/claim.html', 15, 1, 0.067, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/markets.html', 15, 1, 0.067, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/tabletop.html', 15, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/forge.html', 14, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/regina.html', 13, 1, 0.077, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'src/routes/pages.ts', 13, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/collection.html', 13, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/efficiency.html', 13, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/guide.html', 13, 1, 0.077, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/lore.html', 13, 1, 0.077, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/profile-card.html', 13, 1, 0.077, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/citizenship.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/fashion.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/fusion.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/historical-society.html', 12, 1, 0.083, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/pvp.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/staking.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/therapy.html', 12, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/treasury.html', 12, 1, 0.083, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/showcase.html', 11, 2, 0.182, 'medium');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/academy.html', 11, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/conspiracy.html', 11, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'pipeline/keyframes/review.html', 11, 6, 0.545, 'critical');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/apply.html', 11, 1, 0.091, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/arcade.html', 11, 0, 0, 'low');
INSERT INTO hotspots (repo_id, file_path, total_changes, fix_count, fix_rate, risk_level) VALUES ('webapp', 'public/business.html', 11, 0, 0, 'low');

INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-history.json', 'public/static/data/sentinel-report.json', 23, 'strong');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/keyframes/keyframe-manifest.json', 'pipeline/keyframes/review.html', 10, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', '.mycelium/memory.json', 10, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'public/static/data/sentinel-history.json', 10, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'public/static/data/sentinel-report.json', 10, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-history.json', 'public/static/data/showcase-live.json', 8, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', '.mycelium/eval.json', 8, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', '.mycelium/memory.json', 8, 'moderate');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'bin/ai.cjs', 'package.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'EFFICIENCY.md', 'bin/ai.cjs', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/guild/brightinside/assets/paradox-emblem.webp', 'public/guild/brightinside/assets/paradox-lockup.webp', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-report.json', 'public/static/data/showcase-live.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', 'public/static/data/showcase-live.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'public/static/data/showcase-live.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/showcase-live.json', 'scripts/generate-showcase-data.cjs', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/battle.html', 'public/static/data/sentinel-history.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/battle.html', 'public/static/data/sentinel-report.json', 7, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'package.json', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'bin/ai.cjs', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'CLAUDE.md', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', 'public/static/data/showcase-live.json', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'public/static/data/showcase-live.json', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'gitwise.cjs', 'memory.json', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'nw-memory.cjs', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-history.json', 'public/static/nw-battle-engine.js', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-report.json', 'public/static/nw-battle-engine.js', 6, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'EFFICIENCY.md', 'package.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'PROJECT_STATE.md', 'public/guild/brightinside/index.html', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'AI_PLAYBOOK.md', 'bin/ai.cjs', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'README.md', 'docs/cinematic-pipeline.md', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'README.md', 'pipeline/keyframes/keyframe-manifest.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'README.md', 'pipeline/keyframes/review.html', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'docs/cinematic-pipeline.md', 'pipeline/keyframes/keyframe-manifest.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'docs/cinematic-pipeline.md', 'pipeline/keyframes/review.html', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/characters/character-bible.json', 'pipeline/keyframes/keyframe-manifest.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/characters/character-bible.json', 'pipeline/keyframes/review.html', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/keyframes/keyframe-manifest.json', 'pipeline/verification/verification-report.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/keyframes/review.html', 'pipeline/verification/verification-report.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', 'CLAUDE.md', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-history.json', 'scripts/generate-showcase-data.cjs', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.husky/post-commit', 'memory.json', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/nw-nav.js', 'src/index.tsx', 5, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/events.jsonl', '.mycelium/memory.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'PROJECT_STATE.md', 'bin/ai.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'AI_PLAYBOOK.md', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/ai-assets.html', 'public/coin-shop.html', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/ai-assets.html', 'public/kintsugi.html', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/coin-shop.html', 'public/kintsugi.html', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/showcase.html', 'public/static/data/showcase-live.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', 'CLAUDE.md', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', '.mycelium/fix-log.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/fix-log.json', '.mycelium/memory.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.nw-eval-result.json', 'memory.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.nw-eval-result.json', 'public/static/data/showcase-live.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'nw-fixer.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'memory.json', 'scripts/generate-showcase-data.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-report.json', 'scripts/generate-showcase-data.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.husky/post-commit', 'nw-memory.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'gitwise.cjs', 'nw-memory.cjs', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'CLAUDE.md', 'memory.json', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/battle.html', 'public/static/nw-battle-engine.js', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/claim.html', 'public/events.html', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.ai-files-auto.txt', 'public/tabletop.html', 4, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/events.jsonl', 'package.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.gitignore', 'package.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'EFFICIENCY.md', 'bin/session-scorecard.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'bin/ai.cjs', 'bin/session-scorecard.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'bin/session-scorecard.cjs', 'package.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/guild/brightinside/assets/md-reveal.webp', 'public/guild/brightinside/assets/reg-reveal.webp', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'FORGE-DOCTRINE.md', 'TASTE.md', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'FORGE-DOCTRINE.md', 'bin/ai.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'TASTE.md', 'bin/ai.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'EFFICIENCY.md', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'PROJECT_STATE.md', 'public/guild/brightinside/assets/paradox-emblem.webp', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'PROJECT_STATE.md', 'public/guild/brightinside/assets/paradox-lockup.webp', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/guild/brightinside/assets/paradox-emblem.webp', 'tools/asset-alpha-lint.py', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/guild/brightinside/assets/paradox-lockup.webp', 'tools/asset-alpha-lint.py', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/pinforge-stocks.json', 'public/stock/index.html', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/invest.html', 'public/stock/index.html', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'mycelium.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'README.md', 'pipeline/characters/character-bible.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'docs/cinematic-pipeline.md', 'pipeline/characters/character-bible.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'pipeline/characters/character-bible.json', 'pipeline/verification/verification-report.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/markets.html', 'public/static/data/sentinel-history.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/markets.html', 'public/static/data/sentinel-report.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.husky/pre-commit', 'CLAUDE.md', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', 'scripts/generate-showcase-data.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'scripts/generate-showcase-data.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/showcase.html', 'scripts/generate-showcase-data.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', '.mycelium/fix-log.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval-history.json', 'mycelium-eval.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', 'mycelium-eval.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/fix-log.json', 'public/static/data/showcase-live.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'mycelium-eval.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'mycelium-eval.cjs', 'public/static/data/showcase-live.json', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/eval.json', 'bin/mycelium.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/fix-log.json', 'bin/mycelium.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.mycelium/memory.json', 'bin/mycelium.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', 'public/static/data/sentinel-history.json', 'tests/regression-from-breakages.cjs', 3, 'weak');
INSERT INTO coupling (repo_id, file_a, file_b, co_change_count, strength) VALUES ('webapp', '.nw-eval-history.json', '.nw-eval-result.json', 3, 'weak');

INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '0b933b6a3077', '2026-07-05', '9tvf4k6srt-sys', 'fix(learning): ultra-audit — self-healing hooks, honest heartbeat/dashboard, trimmer pattern coverage', 'other', 'ultra-audit-self-healing-hooks-honest', 'critical', 'found: the entire post-commit learning loop was DORMANT', 10, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '844a02ad9d1b', '2026-06-19', '9tvf4k6srt-sys', 'refactor(cli): fix ANSI-leak bug + consolidate duplicated plumbing onto the shared lib', 'logic-error', 'missing-return-statement', 'critical', 'TTY-aware. Measured leak when piped: quality-scorecard 48, deploy-gate 13,', 11, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '437379df7bf3', '2026-06-17', '9tvf4k6srt-sys', 'fix(build): make TSC-0-errors claim true (142 → 0) + add reproducible credibility audit', 'build-config', 'build-config-issue', 'high', 'make TSC-0-errors claim true (142 → 0) + add reproducible credibility audit', 7, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'b8fb2d871d0c', '2026-06-10', '9tvf4k6srt-sys', 'fix(learning): repair the silent heal loop — eval bridge, blame guard, recency-aware health', 'css-layout', 'style-issue', 'critical', 'repair the silent heal loop — eval bridge, blame guard, recency-aware health', 16, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'c880eb90a927', '2026-06-04', 'genspark-ai-developer[bot]', 'revert(guild): switch page music back to the original anime OST (v1) (#105)', 'build-config', 'wrong-asset-path', 'low', 'Changed resource path', 2, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '6cb468d1c7cd', '2026-06-04', 'genspark-ai-developer[bot]', 'fix(guild): music toggle was hidden behind the langbar — move to top-left (#102)', 'css-layout', 'wrong-css-value', 'medium', 'Changed z-index: 40 → 70. Also: z-index: 40 → 70 — stacking context collision; Changed top: 12px → calc(env(safe-area-inset-top, 0px) + 12px)', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '55149f7f86b7', '2026-06-04', 'genspark-ai-developer[bot]', 'fix(learning): rewire the self-improvement stack — live signals, trends→rules, auto-logged efficiency (#98)', 'logic-error', 'missing-return-statement', 'high', 'in two places and the cost meter was unplugged.', 6, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '8ed2bf0e1ae3', '2026-06-04', 'genspark-ai-developer[bot]', 'fix(guild): zoom out the forest backgrounds on iOS + use ALL ambience art (#93)', 'css-layout', 'overflow-hidden-clips-children', 'high', 'Added overflow:hidden — may clip child elements. Also: Added touch event handling — broken on mobile; Changed inset: -4% -4% -4% -4% → 0', 2, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'e713c399f01f', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): rebuild join headline with real word spans + flex gaps (#86)', 'css-layout', 'wrong-css-value', 'medium', 'Changed display: block → flex. Also: Changed display: block → inline-block; Changed margin-top: 0.06em → 0.08em', 1, 0.8);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'd7fbdadd094f', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): keep ROSTER whole on mobile + mobile-first headline sizing (#85)', 'css-layout', 'wrong-css-value', 'low', 'the line is split into per-letter inline-block', 1, 0.8);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '0921c9e1130d', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): preserve word spacing in join headline + stack lines cleanly (#84)', 'css-layout', 'wrong-css-value', 'low', 'Changed font-size: clamp(34px, 10vw, 60px) → clamp(32px, 9.2vw, 60px). Also: Changed line-height: 0.96 → 1.02; Changed letter-spacing: 0.01em → 0.012em', 1, 0.8);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'a51a9be3cc53', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): remove dark island inside P + handle fused-island case in tooling (#82)', 'logic-error', 'missing-return-statement', 'high', 'Added missing return statement — function was returning undefined. Also: Added missing return statement — function was returning undefined', 5, 0.7);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '13d6b3b9c3d8', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): clean demon-P emblem + deterministic emblem pipeline & asset gate (#81)', 'logic-error', 'missing-return-statement', 'high', 'automatically.', 7, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '8b9d70333d4d', '2026-06-03', 'genspark-ai-developer[bot]', 'fix(guild): clean demon-P emblem negative space (#79)', 'other', 'clean-demon-p-emblem-negative', 'medium', 'the background remover only', 2, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'f3d3842a04fc', '2026-06-02', 'genspark-ai-developer[bot]', 'feat(guild): trilingual TH/JA/EN, readability fix, dark-inside origin story (#72)', 'css-layout', 'wrong-css-value', 'medium', 'Changed position: absolute → fixed. Also: Changed z-index: -2 → 0; Changed position: fixed → relative', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '1cadea4bc9e6', '2026-06-02', 'genspark-ai-developer[bot]', 'fix(mining): LLM enrichment now fires (claude-haiku-4-5) + meaning quality gate (#65)', 'other', 'llm-enrichment-now-fires', 'critical', 'fell back to a raw diff', 20, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '0e2c4f573579', '2026-05-02', '9tvf4k6srt-sys', 'fix(invest/liveops): proportional ship speeds calibrated to photo geometry', 'css-layout', 'style-issue', 'medium', 'proportional ship speeds calibrated to photo geometry', 1, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '62d6dd7f6a58', '2026-05-02', '9tvf4k6srt-sys', 'fix(invest/liveops): realistic ship pacing + halved freight + AIS-grade cadences', 'mobile-compat', 'missing-touch-support', 'medium', 'Added touch event handling — broken on mobile. Also: Changed pointer-events: none}
@keyframes loscan{0%,100%{top:8% → none; Changed animation: locloud 24s linear infinite}
@keyframes locloud{0%{transform:translateX(0)}100%{transform:translateX(-12px)}}
/* satellite scanline */
.lo-sat::after{content', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '07babb3e075b', '2026-05-01', '9tvf4k6srt-sys', 'revert(invest): remove Seedance trailer, restore static hero image', 'css-layout', 'wrong-css-value', 'high', 'Changed opacity: .28 → .22. Also: Changed resource path', 7, 0.7);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '90ee99e42af9', '2026-05-01', 'GenSpark AI', 'fix(invest): merch-card mobile overlap — title/body no longer hidden behind photo', 'css-layout', 'overflow-hidden-clips-children', 'high', '(visible on iPhone, narrow viewports):', 1, 0.7);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '5c306d2bdda8', '2026-05-01', '9tvf4k6srt-sys', 'fix(invest): remove ambient audio system + all corner watermark badges', 'css-layout', 'style-issue', 'medium', 'remove ambient audio system + all corner watermark badges', 2, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '33dec5b6958f', '2026-02-16', '9tvf4k6srt-sys', 'fix: Scene 09 v11 — skin tones brightened to #B8875A for cross-scene consistency', 'other', 'scene-v11-skin-tones', 'high', 'Scene 09 v11 — skin tones brightened to #B8875A for cross-scene consistency', 6, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'cbfbf0c0bf55', '2026-02-16', '9tvf4k6srt-sys', 'fix: Scene 09 v8 — DARK skin for RegginA/RegginO, butterfly wings safe, R.M.S. Regina accurate', 'dom-mutation', 'dom-issue', 'medium', 'Scene 09 v8 — DARK skin for RegginA/RegginO, butterfly wings safe, R.M.S. Regina accurate', 4, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '0f389e8ca222', '2026-02-16', '9tvf4k6srt-sys', 'fix: Scene 09 v9 — DARK skin for RegginA/RegginO + accurate R.M.S. Regina', 'test-failure', 'test-issue', 'high', 'Scene 09 v9 — DARK skin for RegginA/RegginO + accurate R.M.S. Regina', 6, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '0be15ffbc62d', '2026-02-16', '9tvf4k6srt-sys', 'feat: repo beautification + scene-10 v4 headband fix', 'api-contract', 'api-contract-issue', 'high', 'feat: repo beautification + scene-10 v4 headband fix', 6, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '68b8bea9c715', '2026-02-15', '9tvf4k6srt-sys', 'fix(scene-10): RegginA headband corrected + CRITICAL_NOTE added to bible', 'other', 'reggina-headband-corrected-criticalnote', 'medium', 'rendered as horns/antlers in v2.', 4, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '8b12e171965a', '2026-02-15', '9tvf4k6srt-sys', 'fix(keyframes): Panthera DARK wings (scene 07 v3) + card deck action (scene 04 v4)', 'other', 'panthera-dark-wings-scene', 'medium', 'Panthera DARK wings (scene 07 v3) + card deck action (scene 04 v4)', 3, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'b4c72a9e1f76', '2026-02-14', 'genspark-ai-developer[bot]', 'feat(pipeline): trailer production pipeline + iOS Safari cinematic fix', 'build-config', 'build-config-issue', 'medium', 'feat(pipeline): trailer production pipeline + iOS Safari cinematic fix', 4, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '5e4bd80eef38', '2026-02-14', 'genspark-ai-developer[bot]', 'fix(cinematic): iOS Safari rewatch — overlay invisible, page content bleeds through', 'css-layout', 'wrong-css-value', 'medium', 'On iOS Safari, position:fixed + pointer-events:none causes the', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '69ea4620e220', '2026-02-14', 'genspark-ai-developer[bot]', 'fix(cinematic): rewatch button dead on returning visitors', 'logic-error', 'missing-return-statement', 'high', 'When the page loaded with localStorage ''nwg_cine_seen'' already set', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '11f9927f63a5', '2026-02-14', 'genspark-ai-developer[bot]', 'fix(cinematic): rewatch loading cue + mobile tap-to-unmute', 'logic-error', 'inverted-boolean-logic', 'medium', 'Tapping Rewatch showed a blank black screen on mobile because:', 1, 0.7);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '34971f87aa8e', '2026-02-14', 'genspark-ai-developer[bot]', 'fix(cinematic): rewrite player for bulletproof mobile touch', 'css-layout', 'wrong-css-value', 'medium', 'Skip button was unresponsive on mobile because:', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '1d25a76cd12d', '2026-02-11', '9tvf4k6srt-sys', 'feat(memory): system audit + AGENT-CONTEXT.md — 26 fixes, hardened validation, portable AI setup', 'other', 'featmemory-system-audit-agent-contextmd', 'medium', 'feat(memory): system audit + AGENT-CONTEXT.md — 26 fixes, hardened validation, portable AI setup', 3, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'd6ae78ebfc84', '2026-02-11', '9tvf4k6srt-sys', 'feat(system): AGENT-CONTEXT.md + full audit fixes', 'mobile-compat', 'missing-responsive-breakpoint', 'high', 'Added responsive breakpoint — was broken on different screen sizes', 5, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '4e6d427f7621', '2026-02-11', '9tvf4k6srt-sys', 'fix: nuke buy-toast entirely — direct redirect to /buy.html, no popup', 'i18n', 'i18n-missing-translation', 'medium', 'nuke buy-toast entirely — direct redirect to /buy.html, no popup', 3, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '3ab2707e758c', '2026-02-11', '9tvf4k6srt-sys', 'fix(ux): bilingual banner, circular coin crop, buy-redirect replaces coming-soon', 'async-timing', 'wrong-timing-value', 'critical', 'Changed timeout: 3500ms → 1200ms', 9, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'f71797da9e64', '2026-02-11', '9tvf4k6srt-sys', 'fix(cleanup): remove Qing/卿 personalization, emoji animations, streak/achievement systems', 'i18n', 'i18n-missing-translation', 'medium', 'remove Qing/卿 personalization, emoji animations, streak/achievement systems', 3, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'f07a57768793', '2026-02-11', '9tvf4k6srt-sys', 'fix(rebrand): add kintsugi.html landing page + update memory to v2 KINTSUGI brand', 'mobile-compat', 'missing-responsive-breakpoint', 'medium', 'Added responsive breakpoint — was broken on different screen sizes', 2, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '26c9c65c87c5', '2026-02-11', '9tvf4k6srt-sys', 'feat(memory): v2.0 hybrid-LTM system — tiered memory, importance scoring, anti-regression guards, retrieval hints', 'other', 'featmemory-v20-hybrid-ltm-system', 'medium', 'feat(memory): v2.0 hybrid-LTM system — tiered memory, importance scoring, anti-regression guards, retrieval hints', 2, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '40f1d8120964', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(showcase): NaN scores, mobile charts 2x, fonts doubled, README rewrite for Mycelium', 'null-reference', 'missing-precondition-check', 'medium', 'Added && guard — was executing without prerequisite check', 4, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'f965e84ef024', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(portable): make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cjs syntax errors, rename .nw-* to .mycelium-*, tested end-to-end on fresh repo', 'test-failure', 'test-issue', 'critical', 'make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cjs syntax errors, rename .nw-* to .mycelium-*, tested end-to-end on fresh repo', 12, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '847fe08950f4', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(honesty): record underselling breakage + add HONESTY GATE to CLAUDE.md — never claim something doesnt work without testing it', 'test-failure', 'test-issue', 'medium', 'record underselling breakage + add HONESTY GATE to CLAUDE.md — never claim something doesnt work without testing it', 4, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'adf49f14d6ed', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(showcase): strip fake impact metrics (hours/money/pts saved) — replace with provable numbers only (33 tests, 13 hardened, 48 learnings, 50 breakages)', 'test-failure', 'test-issue', 'high', 'strip fake impact metrics (hours/money/pts saved) — replace with provable numbers only (33 tests, 13 hardened, 48 learnings, 50 breakages)', 5, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '1998cc926fa4', '2026-02-09', 'genspark-ai-developer[bot]', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed digit-starting i18n key bug in index.html', 'i18n', 'i18n-missing-translation', 'high', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed digit-starting i18n key bug in index.html', 6, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '8f81ad8ef6f5', '2026-02-09', 'genspark-ai-developer[bot]', 'revert(refactor): undo cosmetic file moves + add VALUE GATE constraint — no busywork without measurable improvement', 'other', 'undo-cosmetic-file-moves', 'medium', 'undo cosmetic file moves + add VALUE GATE constraint — no busywork without measurable improvement', 4, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '652f3af88dde', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(ship): sync-back handles stash + CLAUDE.md documents ship as mandatory deploy method', 'css-layout', 'wrong-css-value', 'high', 'Changed run: git checkout main && git pull'') → git checkout main && git pull && git checkout -B genspark_ai_developer main'')', 5, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'dd67dac10b01', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(automation): make learning system fully automatic — no manual heal/eval needed (#13)', 'null-reference', 'missing-precondition-check', 'high', 'selfHeal gated at 10 commits, but squash workflow compresses 4-5→1,', 7, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'd9865b537d92', '2026-02-09', 'genspark-ai-developer[bot]', 'feat(self-heal): auto-eval + auto-fix learning system on every snapshot (#10)', 'error-handling', 'unhandled-exception', 'medium', 'Wrapped code in try-catch — was crashing on error', 3, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '48ba4e3bbe5b', '2026-02-09', 'genspark-ai-developer[bot]', 'fix(hooks): wire gitwise into git hooks + update CLAUDE.md (#8)', 'other', 'wire-gitwise-into-git', 'medium', 'fix: gitwise --warn and --learn calls were dead code (unreachable after exit 0)', 4, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '3affe0355b43', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Auto-start game when overlay isn''t visible on iOS', 'load-order', 'script-order-dependency', 'high', 'showed overlay never appears on iOS mobile — user goes straight to', 4, 0.8);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'e25565d5af73', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Don''t block init on Audio.init() - fixes iOS hand empty bug', 'load-order', 'script-order-dependency', 'high', 'found via mobile debug: init() was stuck at ''await Audio.init()''', 4, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'a64bf8da95c3', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Add mobile debug overlay + cache busting v5.1', 'load-order', 'script-order-dependency', 'high', 'panel (green monospace text at bottom) that shows', 4, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '76de3af642b6', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Move deck building + hand dealing to START button click', 'null-reference', 'missing-precondition-check', 'medium', 'Decks were built and hands dealt during init() (page load),', 3, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '46cec269d4d9', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Mobile hand cards visibility + fix Illegal return statement', 'css-layout', 'overflow-hidden-clips-children', 'high', 'Added overflow:hidden — may clip child elements. Also: Changed cards: fill width with 4px gaps, minimum 64px */
--board-card-width: clamp(64px, calc((100vw - 40px) / 5), 80px) → compact to leave room for hand */
--board-card-width: clamp(56px, calc((100vw - 40px) / 5), 72px); Changed board-card-heig', 5, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '1c919aa627e3', '2026-02-08', '9tvf4k6srt-sys', 'fix(battle): Fix mobile hand cards not visible — arena overflow + flex layout', 'css-layout', 'overflow-hidden-clips-children', 'high', '.arena-container was position:fixed with no overflow,', 3, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'bffff458007e', '2026-02-07', '9tvf4k6srt-sys', 'fix: Restore homepage — remove GSAP defer, fix digit-starting i18n keys', 'other', 'restore-homepage-remove-gsap', 'critical', 'The defer attribute we added to GSAP CDN scripts broke index.html.', 11, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '98b541bdcf02', '2026-02-07', '9tvf4k6srt-sys', 'feat(sentinel): Upgrade to v2.5 — 10-module health platform with trend tracking & auto-fix engine', 'i18n', 'i18n-missing-translation', 'high', 'feat(sentinel): Upgrade to v2.5 — 10-module health platform with trend tracking & auto-fix engine', 5, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'ec3364d0bbb7', '2026-02-06', '9tvf4k6srt-sys', 'fix(cards): Fix language toggle not working', 'null-reference', 'missing-null-guard', 'medium', 'Added 1 optional chaining operator(s) — null reference fix. Also: Added && guard — was executing without prerequisite check; Modified conditional logic', 1, 0.8);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'a8311f88c421', '2026-02-06', '9tvf4k6srt-sys', 'feat(ui): Add UI Guardian v2.0 - automatic overlap detection and fix system', 'other', 'featui-add-guardian-v20', 'medium', 'mode (run NW_UI_GUARDIAN.debug(true))', 2, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '5111c6a471e8', '2026-02-06', '9tvf4k6srt-sys', 'fix(ui): Move card counter to LEFT side - no more overlap', 'css-layout', 'wrong-css-value', 'low', 'Changed bottom: 185px → 130px. Also: Changed left: 50% → 12px; Changed transform: translateX(-50%) → none', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '406af4d94fbe', '2026-02-06', '9tvf4k6srt-sys', 'fix(ui): Larger filter buttons and fix card counter overlap', 'css-layout', 'wrong-css-value', 'medium', 'Changed z-index: 50 → 60. Also: z-index: 50 → 60 — stacking context collision; Changed bottom: 160px → 185px', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '4e5dd99cde6b', '2026-02-06', '9tvf4k6srt-sys', 'fix(ui): Moderate font size increase without overlapping', 'css-layout', 'wrong-css-value', 'low', 'Changed font-size: clamp(24px, 6vw, 36px) → clamp(14px, 4vw, 20px). Also: Changed padding: 8px 14px → 5px 10px; Changed font-size: clamp(24px, 6vw, 36px) → 16px', 2, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '420f4e6ffb56', '2026-02-06', '9tvf4k6srt-sys', 'fix(avatar-studio): Improve mobile touch interactions', 'css-layout', 'overflow-hidden-clips-children', 'high', 'Added overflow:hidden — may clip child elements. Also: Added touch event handling — broken on mobile; Added touch event handling — broken on mobile', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '082b7a66d641', '2026-02-05', '9tvf4k6srt-sys', 'Card #624: Fixed shutter shades (horizontal slats) + asymmetrical hair - workflow learning', 'other', 'card-624-fixed-shutter', 'medium', 'Card #624: Fixed shutter shades (horizontal slats) + asymmetrical hair - workflow learning', 3, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'a3046c009491', '2026-02-05', '9tvf4k6srt-sys', 'Fix: use data-i18n-html for HTML content in wyckoff intro', 'i18n', 'i18n-missing-translation', 'medium', 'use data-i18n-html for HTML content in wyckoff intro', 1, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'd68c51680f3f', '2026-02-05', '9tvf4k6srt-sys', 'Fix Events page JS variable conflicts with i18n.js', 'logic-error', 'missing-return-statement', 'high', 'i18n.js declares ''let pageTranslations'' and ''let currentLang''', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '8c0ab1496c4f', '2026-02-04', '9tvf4k6srt-sys', 'UX: Fix currency display and icon centering', 'dom-mutation', 'innerhtml-destroys-handlers', 'high', 'Replaced innerHTML with textContent — XSS or handler-destruction fix. Also: Added missing return statement — function was returning undefined; Changed font-size: 14px">◆</span><span class="nw-val nwg" id="nwfNwg">0</span></div>'' +
''<div class="nw-item"><span style="font-size:14px">●</span><span clas', 2, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '901f9be71c2b', '2026-02-04', '9tvf4k6srt-sys', 'FIX: Loading screen animations restored', 'css-layout', 'wrong-css-value', 'low', 'Changed height: 120px → 100%. Also: Changed background: linear-gradient(180deg,#ffcc70 0%,#ff9500 30%,#ff6b00 60%,#cc4400 100%) → radial-gradient(ellipse at 20% 20%,rgba(255,107,0,.2) 0%,transparent 50%),radial-gradient(ellipse at 80% 80%,rgba(255,157,77,.15) 0%,transparent 50%); Changed height: 100', 1, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '101f65781ae0', '2026-02-04', '9tvf4k6srt-sys', 'FIX: Optimized currency icons + market page fixes', 'build-config', 'wrong-asset-path', 'low', 'Changed resource path', 4, 0.6);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'ea47b53c1ad9', '2026-02-04', '9tvf4k6srt-sys', 'FIX: Wallet ID loading + currency display', 'null-reference', 'use-before-define', 'high', 'Added typeof !== undefined guard — variable was used before definition. Also: Added missing return statement — function was returning undefined; Added || [] fallback — was calling array method on undefined', 3, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'f4f82980a0ce', '2026-02-04', '9tvf4k6srt-sys', 'FIX: Restore missing currency icons + cleanup', 'other', 'restore-missing-currency-icons', 'high', 'Restore missing currency icons + cleanup', 6, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'fcb85258fb6a', '2026-02-04', '9tvf4k6srt-sys', 'Fix merch.html: null element error crashing product grid render', 'null-reference', 'missing-null-guard', 'medium', 'Added 2 optional chaining operator(s) — null reference fix. Also: Added && guard — was executing without prerequisite check', 1, 0.7);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '717792e9ee0c', '2026-02-04', '9tvf4k6srt-sys', 'Fix merch.html: diamond -> nwg (3-tier currency)', 'other', 'merchhtml-diamond-nwg-3-tier', 'medium', 'merch.html: diamond -> nwg (3-tier currency)', 1, 0.3);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', 'e231b1afe7b6', '2026-02-04', '9tvf4k6srt-sys', 'Fix iOS mobile overlap on Profile Card', 'mobile-compat', 'missing-responsive-breakpoint', 'medium', 'Stats grid was overlapping on small screens due to fixed px positions', 3, 0.9);
INSERT INTO fix_commits (repo_id, commit_hash, commit_date, author, message, category, pattern, severity, root_cause, file_count, confidence) VALUES ('webapp', '7b4ab8d3e2cb', '2026-02-04', '9tvf4k6srt-sys', 'Embassy: fix language toggle + add hero banner', 'i18n', 'i18n-missing-translation', 'medium', 'Embassy: fix language toggle + add hero banner', 3, 0.3);

INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'b710ca48', 'feat(guild): replace eerie ambient with Japanese anime-OST anthem (#103)', '6cb468d1', 'fix(guild): music toggle was hidden behind the langbar — move to top-left (#102)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '998e187f', 'feat(mine): make mined lessons sellable — kill fragments, classify, fresh DB, datavalue scorecard (#', '55149f7f', 'fix(learning): rewire the self-improvement stack — live signals, trends→rules, auto-logged efficienc', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'faa6b65c', 'feat(forge): production doctrine for natural content (words/visual/audio) (#94)', '8ed2bf0e', 'fix(guild): zoom out the forest backgrounds on iOS + use ALL ambience art (#93)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'e713c399', 'fix(guild): rebuild join headline with real word spans + flex gaps (#86)', 'd7fbdadd', 'fix(guild): keep ROSTER whole on mobile + mobile-first headline sizing (#85)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'd7fbdadd', 'fix(guild): keep ROSTER whole on mobile + mobile-first headline sizing (#85)', '0921c9e1', 'fix(guild): preserve word spacing in join headline + stack lines cleanly (#84)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '056505c3', 'feat(guild): Ohm/Omega monogram carved into the demon-P counter (#83)', 'a51a9be3', 'fix(guild): remove dark island inside P + handle fused-island case in tooling (#82)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'a51a9be3', 'fix(guild): remove dark island inside P + handle fused-island case in tooling (#82)', '13d6b3b9', 'fix(guild): clean demon-P emblem + deterministic emblem pipeline & asset gate (#81)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'ed6150d6', 'feat(guild): bolder ember-accented demon-P emblem for dark-bg contrast (#80)', '8b9d7033', 'fix(guild): clean demon-P emblem negative space (#79)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '02423ef1', 'feat(guild): emblem, hero banner, test-server tagline, pay-to-reveal members (#73)', 'f3d3842a', 'feat(guild): trilingual TH/JA/EN, readability fix, dark-inside origin story (#72)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '6ba57404', 'feat(efficiency): monolith page-size guardrail + document the token-conflict trap (#66)', '1cadea4b', 'fix(mining): LLM enrichment now fires (claude-haiku-4-5) + meaning quality gate (#65)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '52c07c53', 'feat(invest/liveops): comprehensive per-vessel analytics + fleet dock', '0e2c4f57', 'fix(invest/liveops): proportional ship speeds calibrated to photo geometry', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '0e2c4f57', 'fix(invest/liveops): proportional ship speeds calibrated to photo geometry', '62d6dd7f', 'fix(invest/liveops): realistic ship pacing + halved freight + AIS-grade cadences', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'd25969c1', 'feat(invest): live ops dashboard — satellite supply chain, NAV vs CPI, AI vote, drawdown, TWSE tape,', '07babb3e', 'revert(invest): remove Seedance trailer, restore static hero image', 24);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'dc90df4d', 'copy(invest/zh): de-LLM sweep — strip classical particles, calque syntax, mirrored EN→ZH structure a', '90ee99e4', 'fix(invest): merch-card mobile overlap — title/body no longer hidden behind photo', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '48cc7d8c', 'feat(invest): per-stock deep-rationale routes for all 12 holdings', '5c306d2b', 'fix(invest): remove ambient audio system + all corner watermark badges', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '8a74f8d5', 'feat: engineering overhaul + Phase 7 — zero TS errors, 94 tests, CI, Biome, Zod, error types, loggin', '33dec5b6', 'fix: Scene 09 v11 — skin tones brightened to #B8875A for cross-scene consistency', 48);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '33dec5b6', 'fix: Scene 09 v11 — skin tones brightened to #B8875A for cross-scene consistency', 'cbfbf0c0', 'fix: Scene 09 v8 — DARK skin for RegginA/RegginO, butterfly wings safe, R.M.S. Regina accurate', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'cbfbf0c0', 'fix: Scene 09 v8 — DARK skin for RegginA/RegginO, butterfly wings safe, R.M.S. Regina accurate', '0f389e8c', 'fix: Scene 09 v9 — DARK skin for RegginA/RegginO + accurate R.M.S. Regina', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '09acb135', 'feat: Harpseal Zakum RegginA raid boss locked + Scene 12 + game page', '0be15ffb', 'feat: repo beautification + scene-10 v4 headband fix', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '7b82ac94', 'feat(dashboard): final pre-trailer review dashboard v5.1', '68b8bea9', 'fix(scene-10): RegginA headband corrected + CRITICAL_NOTE added to bible', 24);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '8f677209', 'feat(keyframes): add characters to SS Regina + Samsara scenes — portray game depth', '8b12e171', 'fix(keyframes): Panthera DARK wings (scene 07 v3) + card deck action (scene 04 v4)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'a3180ce9', 'feat(pipeline): v2 assembler — transitions, music sync, native 9:16 vertical, auto-wrap captions', 'b4c72a9e', 'feat(pipeline): trailer production pipeline + iOS Safari cinematic fix', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '5e4bd80e', 'fix(cinematic): iOS Safari rewatch — overlay invisible, page content bleeds through', '69ea4620', 'fix(cinematic): rewatch button dead on returning visitors', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '69ea4620', 'fix(cinematic): rewatch button dead on returning visitors', '11f9927f', 'fix(cinematic): rewatch loading cue + mobile tap-to-unmute', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '11f9927f', 'fix(cinematic): rewatch loading cue + mobile tap-to-unmute', '34971f87', 'fix(cinematic): rewrite player for bulletproof mobile touch', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '34971f87', 'fix(cinematic): rewrite player for bulletproof mobile touch', 'bb78b867', 'feat: cinematic trailer v3, companion system, Samsara, i18n, mobile skip fix & pipeline', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '30772672', 'feat(item-drops): Legendary Drops item catalog + image compression (#49)', '8a8ca4ba', 'feat(i18n): comprehensive audit tool + DLC 6 Regina + fix orphaned ZH translations', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '035e4b10', 'feat(pcp): NW-AGENT v2.0 — world''s first Project Context Protocol implementation', '2db1ff18', 'feat(i18n+design+siege): Guild Siege page + i18n Guard v2.0 + design guard fixes (#43)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '2db1ff18', 'feat(i18n+design+siege): Guild Siege page + i18n Guard v2.0 + design guard fixes (#43)', '1d25a76c', 'feat(memory): system audit + AGENT-CONTEXT.md — 26 fixes, hardened validation, portable AI setup', 24);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '1d25a76c', 'feat(memory): system audit + AGENT-CONTEXT.md — 26 fixes, hardened validation, portable AI setup', 'd6ae78eb', 'feat(system): AGENT-CONTEXT.md + full audit fixes', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'd6ae78eb', 'feat(system): AGENT-CONTEXT.md + full audit fixes', '4e6d427f', 'fix: nuke buy-toast entirely — direct redirect to /buy.html, no popup', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '4e6d427f', 'fix: nuke buy-toast entirely — direct redirect to /buy.html, no popup', '3ab2707e', 'fix(ux): bilingual banner, circular coin crop, buy-redirect replaces coming-soon', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '3ab2707e', 'fix(ux): bilingual banner, circular coin crop, buy-redirect replaces coming-soon', 'f71797da', 'fix(cleanup): remove Qing/卿 personalization, emoji animations, streak/achievement systems', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'f71797da', 'fix(cleanup): remove Qing/卿 personalization, emoji animations, streak/achievement systems', 'f07a5776', 'fix(rebrand): add kintsugi.html landing page + update memory to v2 KINTSUGI brand', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'ea8793c3', 'feat(rebrand): QinQin Coin → KINTSUGI (KIN) — complete brand overhaul', '26c9c65c', 'feat(memory): v2.0 hybrid-LTM system — tiered memory, importance scoring, anti-regression guards, re', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '175bf371', 'feat(dashboard+learning+data-product): live dashboard, deep compress, validation loop, sale-ready mi', '16c62641', 'refactor: fix stale identifiers, harden init, clean dead code, optimize perf', 24);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'f965e84e', 'fix(portable): make mycelium work on any repo — fix --init crash, strip NumbahWan refs, fix watch.cj', '847fe089', 'fix(honesty): record underselling breakage + add HONESTY GATE to CLAUDE.md — never claim something d', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '847fe089', 'fix(honesty): record underselling breakage + add HONESTY GATE to CLAUDE.md — never claim something d', 'adf49f14', 'fix(showcase): strip fake impact metrics (hours/money/pts saved) — replace with provable numbers onl', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'adf49f14', 'fix(showcase): strip fake impact metrics (hours/money/pts saved) — replace with provable numbers onl', '1998cc92', 'feat(regression): 12 real regression tests targeting actual breakage patterns — caught and fixed dig', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'c2bd51e6', 'feat(hardening): add data-testid to 6 repeat-offender pages (events, pvp, embassy, index, historical', '8f81ad8e', 'revert(refactor): undo cosmetic file moves + add VALUE GATE constraint — no busywork without measura', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'b895bc58', 'feat(eval-v3): honest momentum-aware scoring — sliding window, hardening credit, no gaming', '652f3af8', 'fix(ship): sync-back handles stash + CLAUDE.md documents ship as mandatory deploy method', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '373840d4', 'feat(automation): three-role architecture — Learner + Evaluator + Fixer (#14)', 'dd67dac1', 'fix(automation): make learning system fully automatic — no manual heal/eval needed (#13)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'fa172e0f', 'feat(battle): add battle history stats + match log module (#11)', 'd9865b53', 'feat(self-heal): auto-eval + auto-fix learning system on every snapshot (#10)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '3aab4d9e', 'feat(eval): learning system evaluation — is it getting better or not? (#9)', '48ba4e3b', 'fix(hooks): wire gitwise into git hooks + update CLAUDE.md (#8)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'bb1037f9', 'feat(battle): Complete Battle Arena v6.0 rewrite — mobile-first, tap-to-play', '3affe035', 'fix(battle): Auto-start game when overlay isn''t visible on iOS', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '3affe035', 'fix(battle): Auto-start game when overlay isn''t visible on iOS', 'e25565d5', 'fix(battle): Don''t block init on Audio.init() - fixes iOS hand empty bug', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'e25565d5', 'fix(battle): Don''t block init on Audio.init() - fixes iOS hand empty bug', 'a64bf8da', 'fix(battle): Add mobile debug overlay + cache busting v5.1', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'a64bf8da', 'fix(battle): Add mobile debug overlay + cache busting v5.1', '76de3af6', 'fix(battle): Move deck building + hand dealing to START button click', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '76de3af6', 'fix(battle): Move deck building + hand dealing to START button click', '46cec269', 'fix(battle): Mobile hand cards visibility + fix Illegal return statement', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '46cec269', 'fix(battle): Mobile hand cards visibility + fix Illegal return statement', '1c919aa6', 'fix(battle): Fix mobile hand cards not visible — arena overflow + flex layout', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'e4587940', 'feat(battle): Upgrade to v5.0 — The Funnest Card Game Ever', 'bffff458', 'fix: Restore homepage — remove GSAP defer, fix digit-starting i18n keys', 24);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'bffff458', 'fix: Restore homepage — remove GSAP defer, fix digit-starting i18n keys', 'd0d20984', 'perf: Score 75->82 (B+) — tiered architecture thresholds, API surface dedup fix, 309 scripts deferre', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'f78ac6bf', 'perf: Quick wins batch — score 67 -> 75 (B), 100MB bandwidth saved', '98b541bd', 'feat(sentinel): Upgrade to v2.5 — 10-module health platform with trend tracking & auto-fix engine', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '98b541bd', 'feat(sentinel): Upgrade to v2.5 — 10-module health platform with trend tracking & auto-fix engine', '0abd8031', 'feat(i18n): Auto-fix 70 pages with NW-I18N Auto-Fixer v1.0', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '7c3975b2', 'feat(tooling): Add automatic UI overlap detection system', 'a8311f88', 'feat(ui): Add UI Guardian v2.0 - automatic overlap detection and fix system', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'a8311f88', 'feat(ui): Add UI Guardian v2.0 - automatic overlap detection and fix system', '5111c6a4', 'fix(ui): Move card counter to LEFT side - no more overlap', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '5111c6a4', 'fix(ui): Move card counter to LEFT side - no more overlap', '406af4d9', 'fix(ui): Larger filter buttons and fix card counter overlap', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '406af4d9', 'fix(ui): Larger filter buttons and fix card counter overlap', '4e5dd99c', 'fix(ui): Moderate font size increase without overlapping', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '54d0be08', 'Card #624: Amber Soprano hair now flows heavily down one side like reference', '082b7a66', 'Card #624: Fixed shutter shades (horizontal slats) + asymmetrical hair - workflow learning', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '474e946a', 'COMPLETE: Migrate all 87 pages to unified i18n system', 'ad1c5d29', 'FIX: Unified i18n system - single source of truth', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', '3a81ac8f', 'UPGRADE: Premium currency icons v2.0 (256px)', '101f6578', 'FIX: Optimized currency icons + market page fixes', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'c2ba641c', 'UPGRADE: Premium PNG currency icons (NanoBanana generated)', 'ea47b53c', 'FIX: Wallet ID loading + currency display', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'fcb85258', 'Fix merch.html: null element error crashing product grid render', '717792e9', 'Fix merch.html: diamond -> nwg (3-tier currency)', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'c12c7366', 'HARD RULE #7: 3-Tier Currency System Audit', 'e231b1af', 'Fix iOS mobile overlap on Profile Card', 0);
INSERT INTO fix_chains (repo_id, break_hash, break_message, fix_hash, fix_message, hours_to_fix) VALUES ('webapp', 'a7d85729', 'Embassy: use single lang event listener', '7b4ab8d3', 'Embassy: fix language toggle + add hero banner', 0);
