// AUTO-GENERATED by scripts/compile-content.js — DO NOT EDIT
// Source: content/*.md
// Regenerate: npm run content

export const siteData = {
  "abbot": {
    "config": {
      "background": "/static/images/bg_mandala.webp",
      "overlay": "dark",
      "main_image": "/static/images/abbot1.webp"
    },
    "heading": {
      "heading": {
        "zh": "住持上師",
        "en": "Venerable Abbot",
        "th": "พระอาจารย์เจ้าอาวาส"
      }
    },
    "content": {
      "role": {
        "zh": "如來寺住持",
        "en": "Abbot of Rulai Temple",
        "th": "เจ้าอาวาสวัดรูไหล"
      },
      "bio": {
        "zh": "住持上師為藏傳佛教高僧大德，數十年如一日精進修持，以無上慈悲心弘法利生。上師德高望重，法相莊嚴，持戒精嚴，深受四眾弟子及十方善信之敬仰。",
        "en": "Our Venerable Abbot is a highly accomplished master of Tibetan Buddhism who has devoted decades to diligent practice. With boundless compassion, he spreads the Dharma to benefit all beings. His dignified presence and strict adherence to the precepts have earned deep reverence from disciples and devotees worldwide.",
        "th": "พระอาจารย์เจ้าอาวาสเป็นพระอาจารย์ผู้ทรงคุณวุฒิในพุทธศาสนาทิเบต ผู้อุทิศตนปฏิบัติธรรมมาหลายทศวรรษ ด้วยเมตตากรุณาอันไม่มีประมาณ ท่านเผยแผ่พระธรรมเพื่อประโยชน์แก่สรรพสัตว์"
      },
      "quote": {
        "zh": "「一切有為法，如夢幻泡影，如露亦如電，應作如是觀。」",
        "en": "\"All conditioned phenomena are like dreams, illusions, bubbles, shadows, like dew and lightning; thus should you meditate upon them.\"",
        "th": "\"สรรพสิ่งที่ถูกปรุงแต่งเปรียบเสมือนความฝัน ภาพลวง ฟองสบู่ เงา เสมือนน้ำค้างและสายฟ้า พึงพิจารณาดังนี้\""
      }
    }
  },
  "about": {
    "config": {
      "background": "/static/images/reno_wide.webp",
      "overlay": "default"
    },
    "heading": {
      "heading": {
        "zh": "關於如來寺",
        "en": "About Rulai Temple",
        "th": "เกี่ยวกับวัดรูไหล"
      }
    },
    "cards": [
      {
        "name": "Tibetan Buddhist Lineage",
        "icon": "ico-om",
        "animation": "reveal-left",
        "title": {
          "zh": "藏傳佛教傳承",
          "en": "Tibetan Buddhist Lineage",
          "th": "สายพุทธทิเบต"
        },
        "body": {
          "zh": "如來寺承繼藏傳佛教殊勝法脈，弘揚顯密圓融之教法，以慈悲與智慧引導眾生趣向解脫之道。",
          "en": "Rulai Temple carries the precious lineage of Tibetan Buddhism, spreading the harmonious teachings of exoteric and esoteric Buddhism, guiding all beings toward liberation through compassion and wisdom.",
          "th": "วัดรูไหลสืบทอดสายธรรมอันล้ำค่าของพุทธศาสนาทิเบต เผยแผ่คำสอนทั้งเปิดเผยและลึกซึ้ง นำพาสรรพสัตว์สู่ความหลุดพ้นด้วยกรุณาและปัญญา"
        }
      },
      {
        "name": "Thriving Spiritual Energy",
        "icon": "ico-fire",
        "animation": "reveal-up",
        "title": {
          "zh": "香火鼎盛",
          "en": "Thriving Spiritual Energy",
          "th": "พลังจิตวิญญาณรุ่งเรือง"
        },
        "body": {
          "zh": "如來寺香火鼎盛，信眾遍及海內外。每日晨鐘暮鼓，梵音繚繞，護佑十方善信消災祈福，功德無量。",
          "en": "Rulai Temple thrives with spiritual energy, attracting devotees from across the world. Morning bells and evening drums echo daily, protecting all faithful followers with boundless merit.",
          "th": "วัดรูไหลเต็มไปด้วยพลังจิตวิญญาณ ดึงดูดศรัทธาจากทั่วโลก ระฆังเช้าและกลองเย็นก้องทุกวัน ปกป้องศรัทธาชนทั้งปวงด้วยบุญกุศลอันไม่มีประมาณ"
        }
      },
      {
        "name": "Ceremonies & Practice",
        "icon": "ico-pray",
        "animation": "reveal-right",
        "title": {
          "zh": "法會與修持",
          "en": "Ceremonies & Practice",
          "th": "พิธีกรรมและการปฏิบัติ"
        },
        "body": {
          "zh": "定期舉辦藏傳佛教法會、灌頂、超渡法會、放生法會等殊勝佛事活動，廣結善緣，普度眾生。",
          "en": "Regular Tibetan Buddhist ceremonies including empowerment rituals, liberation ceremonies, and life-release events, creating positive karmic connections for all beings.",
          "th": "พิธีกรรมทางพุทธศาสนาทิเบตเป็นประจำ รวมถึงพิธีเสริมพลัง พิธีปลดปล่อย และกิจกรรมปล่อยชีวิต สร้างสายสัมพันธ์แห่งกรรมดีแก่สรรพสัตว์"
        }
      }
    ]
  },
  "gallery": {
    "config": {
      "background": "/static/images/bg_temple.webp",
      "overlay": "dark"
    },
    "heading": {
      "heading": {
        "zh": "上師法相",
        "en": "Venerable Abbot Gallery",
        "th": "แกลเลอรีพระอาจารย์"
      }
    },
    "images": [
      {
        "src": "/static/images/abbot1.webp",
        "alt": "住持法相",
        "zh": "住持上師 · 法相莊嚴",
        "en": "Venerable Abbot · Dignified Presence",
        "th": "พระอาจารย์ · พระพักตร์อันสง่างาม"
      },
      {
        "src": "/static/images/abbot2.webp",
        "alt": "住持側影",
        "zh": "禪定中的上師",
        "en": "The Master in Meditation",
        "th": "พระอาจารย์ในสมาธิ"
      },
      {
        "src": "/static/images/abbot3.webp",
        "alt": "住持開示",
        "zh": "弘法利生",
        "en": "Spreading Dharma",
        "th": "เผยแผ่พระธรรม"
      },
      {
        "src": "/static/images/abbot4.webp",
        "alt": "住持禪修",
        "zh": "慈悲觀照",
        "en": "Compassionate Contemplation",
        "th": "การพิจารณาด้วยกรุณา"
      },
      {
        "src": "/static/images/abbot5.webp",
        "alt": "住持加持",
        "zh": "大德風範",
        "en": "Noble Bearing",
        "th": "ท่าทางอันสูงส่ง"
      }
    ]
  },
  "hero": {
    "logo": {
      "nav_logo": "/static/images/logo_nav.webp",
      "hero_logo": "/static/images/logo_med.webp",
      "full_logo": "/static/images/logo.webp",
      "background": "/static/images/bg_hero.webp"
    },
    "content": {
      "loader_text": {
        "zh": "如來寺",
        "en": "Rulai Temple",
        "th": "วัดรูไหล"
      },
      "nav_title": {
        "zh": "如來寺",
        "en": "Rulai Temple",
        "th": "วัดรูไหล"
      },
      "title": {
        "zh": "如來寺",
        "en": "Rulai Temple",
        "th": "วัดรูไหล"
      },
      "subtitle": {
        "zh": "台灣雲林縣斗六市 · 藏傳佛教聖地",
        "en": "Douliu, Yunlin County, Taiwan · Tibetan Buddhist Sacred Ground",
        "th": "โต้วลิ่ว หยุนหลิน ไต้หวัน · ดินแดนศักดิ์สิทธิ์แห่งพุทธศาสนาทิเบต"
      },
      "mantra": {
        "zh": "ༀ མ་ཎི་པདྨེ་ཧཱུྃ",
        "en": "Om Mani Padme Hum",
        "th": "โอม มณี ปัทเม ฮุม"
      },
      "cta": {
        "zh": "探索聖地",
        "en": "Explore Sacred Ground",
        "th": "สำรวจดินแดนศักดิ์สิทธิ์"
      }
    }
  },
  "history": {
    "config": {
      "background": "/static/images/bg_history.webp",
      "overlay": "dark"
    },
    "heading": {
      "heading": {
        "zh": "如來寺緣起",
        "en": "Our Sacred Origin",
        "th": "ประวัติวัดรูไหล"
      }
    },
    "items": [
      {
        "name": "1949 — Founding",
        "year": "1949",
        "icon": "ico-incense",
        "animation": "reveal-left",
        "title": {
          "zh": "王居士 · 一念慈悲 · 創建如來寺",
          "en": "Lay Buddhist Wang · A Compassionate Vow · Founded Rulai Temple",
          "th": "อุบาสิกาหวัง · ปณิธานแห่งกรุณา · ก่อตั้งวัดรูไหล"
        },
        "body": {
          "zh": "民國三十八年（1949），王居士以畢生心血創立如來寺。她將一生的積蓄與努力，全數投注於這片佛土之上，只為一個樸實的心願——造福身邊的每一個人。她深信佛法的力量能夠改變世間苦難，以無私的奉獻精神，在雲林斗六這片土地上，種下了一顆慈悲的種子。",
          "en": "In 1949, the devout Lay Buddhist Wang devoted her entire life's work to founding Rulai Temple. She poured all her savings and efforts into this sacred ground, driven by one simple and pure wish — to bring blessings and welfare to everyone around her. With unwavering faith in the transformative power of the Dharma, she planted a seed of compassion in the soil of Douliu, Yunlin.",
          "th": "ในปี 1949 อุบาสิกาหวังผู้เลื่อมใสอุทิศผลงานทั้งชีวิตเพื่อก่อตั้งวัดรูไหล เธอทุ่มเททรัพย์สินและความพยายามทั้งหมดในดินแดนศักดิ์สิทธิ์แห่งนี้ ด้วยความปรารถนาอันบริสุทธิ์เพียงหนึ่งเดียว — เพื่อนำพรและความเป็นอยู่ที่ดีมาสู่ทุกคนรอบข้าง"
        }
      },
      {
        "name": "Legacy — Dual Cultivation",
        "year_zh": "傳承",
        "year_en": "Legacy",
        "year_th": "สืบทอด",
        "icon": "ico-dharma",
        "animation": "reveal-right",
        "title": {
          "zh": "顯宗密宗雙修 · 獨一無二的修行道場",
          "en": "Dual Cultivation of Exoteric & Esoteric Buddhism · A Unique Sacred Ground",
          "th": "การปฏิบัติทั้งเปิดเผยและลึกซึ้ง · สถานที่ศักดิ์สิทธิ์อันเป็นเอกลักษณ์"
        },
        "body": {
          "zh": "如來寺是極為殊勝的顯宗密宗雙修道場。在台灣，同時兼修顯教與密教的寺院非常稀有。如來寺融合兩大法門之精華，令修行者既能深入經藏、通達教理，又能修持密法、獲得加持。這種圓融無礙的修行方式，使如來寺的靈驗程度與其他道場有著顯著的不同。",
          "en": "Rulai Temple is an exceptionally rare sacred ground where both Exoteric (Sutra) and Esoteric (Tantra) Buddhism are practiced together. In Taiwan, temples that cultivate both traditions simultaneously are extremely scarce. By merging the essence of both paths, practitioners can deeply study the sutras while also receiving the blessings of esoteric practices. This harmonious approach makes Rulai Temple's spiritual efficacy remarkably different from other institutions.",
          "th": "วัดรูไหลเป็นสถานที่ศักดิ์สิทธิ์อันหายากยิ่ง ซึ่งปฏิบัติทั้งพุทธศาสนาแบบเปิดเผย (สูตร) และแบบลึกซึ้ง (ตันตระ) ร่วมกัน ในไต้หวัน วัดที่เจริญทั้งสองสายพร้อมกันนั้นหายากมาก การผสมผสานแก่นแท้ของทั้งสองเส้นทาง ทำให้ประสิทธิผลทางจิตวิญญาณของวัดรูไหลแตกต่างอย่างเห็นได้ชัดจากสถาบันอื่น"
        }
      },
      {
        "name": "Present — Enduring Legacy",
        "year_zh": "今日",
        "year_en": "Today",
        "year_th": "ปัจจุบัน",
        "icon": "ico-fire",
        "animation": "reveal-left",
        "title": {
          "zh": "七十餘載 · 香火不絕 · 靈驗有別",
          "en": "Over 75 Years · Unceasing Devotion · Extraordinary Efficacy",
          "th": "กว่า 75 ปี · ศรัทธาไม่เคยหยุด · ประสิทธิผลอันพิเศษ"
        },
        "body": {
          "zh": "自1949年至今，如來寺已走過七十餘載春秋。王居士當年播下的慈悲種子，如今已成長為庇蔭萬千信眾的菩提大樹。如來寺的靈驗程度與其他單位有別，無數信眾在此獲得感應與庇佑，口耳相傳，香火日益鼎盛。",
          "en": "From 1949 to today, Rulai Temple has endured over 75 years. The seed of compassion that Lay Buddhist Wang planted has grown into a great Bodhi tree sheltering thousands of devotees. The temple's spiritual efficacy is remarkably different from other institutions — countless devotees have experienced profound blessings here, and word-of-mouth has made the temple's spiritual energy ever more vibrant.",
          "th": "ตั้งแต่ปี 1949 จนถึงปัจจุบัน วัดรูไหลผ่านมากว่า 75 ปี เมล็ดพันธุ์แห่งกรุณาที่อุบาสิกาหวังปลูกไว้ได้เติบโตเป็นต้นโพธิ์ใหญ่ที่ร่มเงาแก่ศรัทธาชนนับพัน ประสิทธิผลทางจิตวิญญาณของวัดแตกต่างอย่างเห็นได้ชัดจากสถาบันอื่น"
        }
      }
    ]
  },
  "services": {
    "config": {
      "background": "/static/images/bg_altar.webp",
      "overlay": "default"
    },
    "heading": {
      "heading": {
        "zh": "殊勝服務 · 加持結緣",
        "en": "Sacred Services & Blessed Connections",
        "th": "บริการอันศักดิ์สิทธิ์และสายสัมพันธ์แห่งพร"
      }
    },
    "notice": {
      "notice": {
        "zh": "⚠ 如來寺所有結緣物品皆經住持上師親自加持修法，未經加持不予結緣。每一件法物皆承載殊勝願力與佛力加持。",
        "en": "⚠ All items shared at Rulai Temple have been personally blessed and empowered by the Venerable Abbot through sacred rituals. No item is given without proper consecration. Every sacred object carries extraordinary votive power and Buddha's blessings.",
        "th": "⚠ สิ่งศักดิ์สิทธิ์ทุกชิ้นที่วัดรูไหลได้รับการเสกและเสริมพลังโดยพระอาจารย์เจ้าอาวาสด้วยตนเองผ่านพิธีกรรมศักดิ์สิทธิ์ ไม่มีสิ่งใดถูกมอบให้โดยไม่ผ่านการปลุกเสก"
      }
    },
    "cta": {
      "cta": {
        "zh": "歡迎十方善信前來如來寺參觀、祈福、結緣",
        "en": "All devotees are warmly welcome to visit Rulai Temple for prayers and blessings",
        "th": "ยินดีต้อนรับศรัทธาชนทุกท่านมาเยี่ยมชมวัดรูไหลเพื่อสวดภาวนาและรับพร"
      }
    },
    "services": [
      {
        "name": "Resolving Karmic Matters",
        "icon": "ico-vajra",
        "featured": "false",
        "title": {
          "zh": "化解事情",
          "en": "Resolving Karmic Matters",
          "th": "การแก้ไขเรื่องกรรม"
        },
        "body": {
          "zh": "住持上師以深厚修為與殊勝法力，協助信眾化解生活中的種種困難與障礙。無論是事業、家庭、健康或人際關係上的困擾，上師皆能以佛法智慧為您指引方向、消除業障。",
          "en": "The Venerable Abbot uses his profound spiritual cultivation and sacred powers to help devotees resolve life's difficulties and obstacles. Whether in career, family, health, or relationships — the Abbot guides you with the wisdom of the Dharma to remove karmic hindrances.",
          "th": "พระอาจารย์เจ้าอาวาสใช้การบำเพ็ญเพียรทางจิตวิญญาณอันลึกซึ้งและพลังศักดิ์สิทธิ์เพื่อช่วยศรัทธาชนแก้ไขปัญหาชีวิต ไม่ว่าจะเป็นอาชีพ ครอบครัว สุขภาพ หรือความสัมพันธ์"
        }
      },
      {
        "name": "Blessing Lamp Lighting",
        "icon": "ico-lamp",
        "featured": "false",
        "title": {
          "zh": "點燈祈福",
          "en": "Blessing Lamp Lighting",
          "th": "จุดตะเกียงอธิษฐาน"
        },
        "body": {
          "zh": "為信眾點燈祈福，以光明照破黑暗，祈求平安吉祥、消災延壽。每盞燈皆由上師親自加持誦經，燈火所照之處，佛光普照，功德無量。",
          "en": "Lighting sacred blessing lamps for devotees — illuminating darkness with light, praying for peace, auspiciousness, and longevity. Each lamp is personally consecrated by the Abbot with sutra recitation. Where the lamp shines, Buddha's light radiates with boundless merit.",
          "th": "จุดตะเกียงอธิษฐานอันศักดิ์สิทธิ์เพื่อศรัทธาชน ส่องสว่างความมืดด้วยแสง สวดภาวนาเพื่อสันติสุข มงคล และอายุยืน ตะเกียงแต่ละดวงได้รับการปลุกเสกโดยเจ้าอาวาสด้วยตนเอง"
        }
      },
      {
        "name": "Empowered Sacred Items",
        "icon": "ico-mala",
        "featured": "false",
        "title": {
          "zh": "加持法物",
          "en": "Empowered Sacred Items",
          "th": "วัตถุมงคลที่ปลุกเสก"
        },
        "body": {
          "zh": "所有結緣給信眾的物品——佛珠、護身符、經文、法器等——皆經過住持上師特殊法式加持修法。未經加持的物品，絕不結緣。這是如來寺對每一位信眾最誠摯的承諾與尊重。",
          "en": "Every item shared with devotees — prayer beads, amulets, sutras, ritual implements — has undergone special consecration rituals by the Abbot. Items without proper empowerment are never given out. This is Rulai Temple's sincere promise and respect to every devotee.",
          "th": "ทุกสิ่งที่แบ่งปันกับศรัทธาชน — ลูกประคำ เครื่องราง พระสูตร เครื่องมือพิธีกรรม — ผ่านพิธีปลุกเสกพิเศษโดยเจ้าอาวาส สิ่งของที่ไม่ผ่านการเสริมพลังจะไม่ถูกมอบให้ นี่คือคำมั่นสัญญาอันจริงใจของวัดรูไหลต่อศรัทธาชนทุกคน"
        }
      },
      {
        "name": "Karmic Debt Resolution Golden Bars",
        "icon": "ico-goldbar",
        "featured": "true",
        "title": {
          "zh": "冤親債主解怨金條",
          "en": "Karmic Debt Resolution Golden Bars",
          "th": "แท่งทองแก้กรรมเจ้ากรรมนายเวร"
        },
        "body": {
          "zh": "如來寺特有的殊勝法物——冤親債主解怨金條。專門用於化解累世冤親債主之間的怨結與業力糾纏。每一根金條皆經過特殊法式修持加持，注入殊勝佛力，幫助信眾與冤親債主達成和解，消除宿世業障，獲得身心自在。歡迎有緣者前來參觀了解。",
          "en": "Rulai Temple's unique and precious sacred item — the Karmic Debt Resolution Golden Bars. Specially designed to resolve karmic entanglements and grudges with karmic creditors from past lives. Each golden bar undergoes special ritual consecration, infused with extraordinary Buddha-power, helping devotees achieve reconciliation with karmic creditors, eliminating karmic obstacles, and attaining freedom of body and mind. Visitors are warmly welcome to come learn more.",
          "th": "วัตถุมงคลอันเป็นเอกลักษณ์ของวัดรูไหล — แท่งทองแก้กรรมเจ้ากรรมนายเวร ออกแบบมาเพื่อแก้ไขความพัวพันทางกรรมและความแค้นกับเจ้ากรรมนายเวรจากอดีตชาติ แท่งทองแต่ละแท่งผ่านพิธีปลุกเสกพิเศษ เติมเต็มด้วยพลังพุทธคุณอันพิเศษ ช่วยศรัทธาชนบรรลุการปรองดองกับเจ้ากรรมนายเวร ยินดีต้อนรับผู้มีบุญมาเยี่ยมชม"
        }
      }
    ]
  },
  "site": {
    "meta": {
      "title_zh": "如來寺 Rulai Temple — 藏傳佛教聖地",
      "title_en": "Rulai Temple — Tibetan Buddhist Sacred Ground",
      "title_th": "วัดรูไหล — ดินแดนศักดิ์สิทธิ์แห่งพุทธศาสนาทิเบต",
      "description_zh": "台灣雲林縣斗六市如來寺 - 藏傳佛教聖地",
      "description_en": "Rulai Temple in Douliu, Yunlin, Taiwan - Tibetan Buddhist Sacred Ground",
      "description_th": "วัดรูไหลในโต้วลิ่ว หยุนหลิน ไต้หวัน - ดินแดนศักดิ์สิทธิ์แห่งพุทธศาสนาทิเบต",
      "favicon": "/static/favicon.ico",
      "copyright_year": "2024",
      "mantra": "ༀ མ་ཎི་པདྨེ་ཧཱུྃ"
    },
    "langs": [
      {
        "code": "zh",
        "label": "中文"
      },
      {
        "code": "en",
        "label": "EN"
      },
      {
        "code": "th",
        "label": "ไทย"
      }
    ],
    "nav": [
      {
        "id": "hero",
        "zh": "首頁",
        "en": "Home",
        "th": "หน้าแรก"
      },
      {
        "id": "history",
        "zh": "緣起",
        "en": "Origin",
        "th": "ประวัติ"
      },
      {
        "id": "about",
        "zh": "關於",
        "en": "About",
        "th": "เกี่ยวกับ"
      },
      {
        "id": "abbot",
        "zh": "住持",
        "en": "Abbot",
        "th": "เจ้าอาวาส"
      },
      {
        "id": "services",
        "zh": "服務",
        "en": "Services",
        "th": "บริการ"
      },
      {
        "id": "gallery",
        "zh": "法相",
        "en": "Gallery",
        "th": "แกลเลอรี"
      },
      {
        "id": "vision",
        "zh": "願景",
        "en": "Vision",
        "th": "วิสัยทัศน์"
      },
      {
        "id": "visit",
        "zh": "參訪",
        "en": "Visit",
        "th": "เยี่ยมชม"
      }
    ],
    "scripts": [
      {
        "library": "GSAP",
        "url": "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"
      },
      {
        "library": "ScrollTrigger",
        "url": "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"
      }
    ],
    "footer": {
      "copyright": {
        "zh": "© 2024 如來寺 · 台灣雲林縣斗六市 · 一切功德迴向法界眾生",
        "en": "© 2024 Rulai Temple · Douliu, Yunlin, Taiwan · All merit dedicated to sentient beings",
        "th": "© 2024 วัดรูไหล · โต้วลิ่ว หยุนหลิน ไต้หวัน · อุทิศบุญกุศลแก่สรรพสัตว์"
      }
    }
  },
  "trailer": {
    "config": {
      "video_src": "/static/trailer.mp4",
      "poster": "/static/images/bg_temple.webp"
    },
    "content": {
      "heading": {
        "zh": "如來寺巡禮",
        "en": "Temple Flythrough",
        "th": "ชมบรรยากาศวัด"
      },
      "play_btn": {
        "zh": "播放巡禮",
        "en": "Play Tour",
        "th": "เล่นวิดีโอ"
      },
      "caption": {
        "zh": "空拍鏡頭帶您走進如來寺 · 感受藏傳佛教的莊嚴氛圍",
        "en": "A cinematic drone tour through Rulai Temple · Experience the majesty of Tibetan Buddhist sacred space",
        "th": "ทัวร์โดรนผ่านวัดรูไหล · สัมผัสความงดงามของพุทธสถานทิเบต"
      }
    }
  },
  "vision": {
    "config": {
      "background": "/static/images/bg_mandala.webp",
      "overlay": "dark"
    },
    "heading": {
      "heading": {
        "zh": "道場願景 · 藏傳佛教大殿",
        "en": "Temple Vision · Tibetan Buddhist Renovation",
        "th": "วิสัยทัศน์วัด · การบูรณะแบบพุทธทิเบต"
      }
    },
    "intro": {
      "intro": {
        "zh": "如來寺即將迎來藏傳佛教風格的全面大裝修，以下為規劃願景圖。我們將以最莊嚴殊勝的藏式裝修，打造台灣最具代表性的顯密雙修道場。",
        "en": "Rulai Temple is planning a comprehensive Tibetan Buddhist renovation. Below are the envisioned designs. We will create the most dignified and sacred Tibetan-style sanctuary — Taiwan's premier dual-practice temple.",
        "th": "วัดรูไหลกำลังวางแผนบูรณะครั้งใหญ่ในรูปแบบพุทธทิเบต ด้านล่างคือภาพออกแบบที่วางไว้ เราจะสร้างวิหารทิเบตที่สง่างามและศักดิ์สิทธิ์ที่สุด"
      }
    },
    "renders": [
      {
        "src": "/static/images/reno_ext1.webp",
        "alt": "外觀裝修",
        "large": true,
        "zh": "外觀 · 藏式山門",
        "en": "Exterior · Tibetan Gate",
        "th": "ภายนอก · ประตูทิเบต"
      },
      {
        "src": "/static/images/reno_ext2.webp",
        "alt": "外觀側面",
        "large": false,
        "zh": "外觀 · 經幡莊嚴",
        "en": "Exterior · Prayer Flags",
        "th": "ภายนอก · ธงมนตรา"
      },
      {
        "src": "/static/images/reno_altar.webp",
        "alt": "佛壇",
        "large": false,
        "zh": "佛壇 · 酥油燈供",
        "en": "Altar · Butter Lamps",
        "th": "แท่นบูชา · ตะเกียงเนย"
      },
      {
        "src": "/static/images/reno_int1.webp",
        "alt": "大殿全景",
        "large": true,
        "zh": "大殿 · 唐卡莊嚴",
        "en": "Main Hall · Thangka Gallery",
        "th": "ห้องโถงใหญ่ · ทังกา"
      },
      {
        "src": "/static/images/reno_int2.webp",
        "alt": "法會場景",
        "large": false,
        "zh": "法會 · 藏式儀軌",
        "en": "Ceremony · Tibetan Rituals",
        "th": "พิธี · พิธีกรรมทิเบต"
      },
      {
        "src": "/static/images/reno_wide.webp",
        "alt": "廣角大殿",
        "large": false,
        "zh": "大殿 · 全景莊嚴",
        "en": "Hall · Grand Panorama",
        "th": "ห้องโถง · มุมกว้าง"
      }
    ]
  },
  "visit": {
    "config": {
      "background": "/static/images/reno_int1.webp",
      "overlay": "default"
    },
    "heading": {
      "heading": {
        "zh": "參訪如來寺",
        "en": "Visit Rulai Temple",
        "th": "เยี่ยมชมวัดรูไหล"
      }
    },
    "cards": [
      {
        "name": "Address",
        "icon": "ico-pin",
        "animation": "reveal-left",
        "title": {
          "zh": "寺院地址",
          "en": "Address",
          "th": "ที่อยู่"
        },
        "body": {
          "zh": "雲林縣斗六市",
          "en": "Douliu City, Yunlin County, Taiwan",
          "th": "เมืองโต้วลิ่ว จังหวัดหยุนหลิน ไต้หวัน"
        }
      },
      {
        "name": "Open Hours",
        "icon": "ico-clock",
        "animation": "reveal-up",
        "title": {
          "zh": "開放時間",
          "en": "Open Hours",
          "th": "เวลาทำการ"
        },
        "body": {
          "zh": "每日 06:00 - 18:00",
          "en": "Daily 06:00 - 18:00",
          "th": "ทุกวัน 06:00 - 18:00"
        }
      },
      {
        "name": "Contact",
        "icon": "ico-phone",
        "animation": "reveal-right",
        "title": {
          "zh": "聯繫方式",
          "en": "Contact",
          "th": "ติดต่อ"
        },
        "body": {
          "zh": "歡迎來電洽詢",
          "en": "Welcome to call for inquiries",
          "th": "ยินดีต้อนรับการสอบถาม"
        }
      }
    ]
  }
} as const;

export type SiteData = typeof siteData;
