#!/usr/bin/env node
/**
 * Unified Event Bus v1.0
 * ═══════════════════════════════════════════════════════════════
 * Central event log that all learning systems write to.
 * Enables cross-system feedback loops.
 *
 * Events are append-only JSONL (newline-delimited JSON).
 * Each event: { ts, system, event, severity, data }
 *
 * Systems that emit events:
 *   - vitest (test_pass, test_fail, suite_complete)
 *   - tsc (type_error, type_clean)
 *   - biome (lint_error, lint_clean)
 *   - sentinel (score_change, heal_run, guard_fail)
 *   - ci (gate_pass, gate_fail, pipeline_complete)
 *   - build (build_success, build_fail, bundle_size)
 *   - mycelium (breakage, learning, constraint, snapshot)
 *
 * Usage:
 *   node tools/event-bus.cjs emit --system=vitest --event=test_fail --data='{"file":"x.test.ts"}'
 *   node tools/event-bus.cjs query --system=vitest --last=10
 *   node tools/event-bus.cjs process     # Process unprocessed events into learnings
 *   node tools/event-bus.cjs stats       # Show event statistics
 *   node tools/event-bus.cjs trim        # Trim events older than 30 days
 *
 * @version 1.0.0
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const EVENTS_FILE = path.join(ROOT, '.mycelium', 'events.jsonl')
const MEMORY_FILE = path.join(ROOT, '.mycelium', 'memory.json')
const MAX_EVENTS = 5000
const MAX_AGE_DAYS = 30

// ── Helpers ─────────────────────────────────────────────────
function ensureDir(fp) {
  const dir = path.dirname(fp)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
}

function readEvents() {
  if (!fs.existsSync(EVENTS_FILE)) return []
  return fs.readFileSync(EVENTS_FILE, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map(line => { try { return JSON.parse(line) } catch { return null } })
    .filter(Boolean)
}

function appendEvent(event) {
  ensureDir(EVENTS_FILE)
  const record = {
    ts: Date.now(),
    date: new Date().toISOString(),
    ...event,
  }
  fs.appendFileSync(EVENTS_FILE, JSON.stringify(record) + '\n')
  return record
}

function readMemory() {
  try { return JSON.parse(fs.readFileSync(MEMORY_FILE, 'utf8')) } catch { return null }
}

function writeMemory(mem) {
  fs.writeFileSync(MEMORY_FILE, JSON.stringify(mem, null, 2))
}

// ── Event Processing: Convert events into learnings/breakages ─
function processEvents() {
  const events = readEvents()
  const mem = readMemory()
  if (!mem) { console.log('No memory.json found'); return }

  const processed = new Set()
  const processedFile = EVENTS_FILE + '.processed'
  if (fs.existsSync(processedFile)) {
    fs.readFileSync(processedFile, 'utf8').split('\n').filter(Boolean).forEach(ts => processed.add(ts))
  }

  let newBreakages = 0
  let newLearnings = 0

  for (const evt of events) {
    if (processed.has(String(evt.ts))) continue

    // Test failures → breakages
    if (evt.event === 'test_fail') {
      if (!mem.breakages) mem.breakages = []
      mem.breakages.push({
        ts: evt.ts,
        date: evt.date?.split('T')[0] || new Date(evt.ts).toISOString().split('T')[0],
        area: 'backend',
        what: `Test failed: ${evt.data?.file || 'unknown'} — ${evt.data?.testName || evt.data?.error || 'assertion error'}`,
        source: `event-bus:${evt.system}`,
      })
      newBreakages++
    }

    // TypeScript errors → learnings
    if (evt.event === 'type_error') {
      if (!mem.learnings) mem.learnings = []
      mem.learnings.push({
        ts: evt.ts,
        date: evt.date?.split('T')[0] || new Date(evt.ts).toISOString().split('T')[0],
        area: 'typescript',
        lesson: `TS${evt.data?.code || '????'} in ${evt.data?.file || 'unknown'}: ${evt.data?.message || 'type error'}. Fix: ensure explicit types.`,
        autoGenerated: true,
        source: `event-bus:tsc`,
      })
      newLearnings++
    }

    // Lint errors → learnings
    if (evt.event === 'lint_error') {
      if (!mem.learnings) mem.learnings = []
      mem.learnings.push({
        ts: evt.ts,
        date: evt.date?.split('T')[0] || new Date(evt.ts).toISOString().split('T')[0],
        area: 'lint',
        lesson: `Biome ${evt.data?.rule || 'unknown'} in ${evt.data?.file || 'unknown'}: ${evt.data?.message || 'lint violation'}`,
        autoGenerated: true,
        source: `event-bus:biome`,
      })
      newLearnings++
    }

    // Score drops → breakages
    if (evt.event === 'score_drop') {
      if (!mem.breakages) mem.breakages = []
      mem.breakages.push({
        ts: evt.ts,
        date: evt.date?.split('T')[0] || new Date(evt.ts).toISOString().split('T')[0],
        area: 'health',
        what: `Health score dropped: ${evt.data?.from || '?'} → ${evt.data?.to || '?'} (module: ${evt.data?.module || 'composite'})`,
        source: `event-bus:sentinel`,
      })
      newBreakages++
    }

    // Bundle size alerts → learnings
    if (evt.event === 'bundle_alert') {
      if (!mem.learnings) mem.learnings = []
      mem.learnings.push({
        ts: evt.ts,
        date: evt.date?.split('T')[0] || new Date(evt.ts).toISOString().split('T')[0],
        area: 'performance',
        lesson: `Bundle size ${evt.data?.sizeKB || '?'}KB exceeds budget ${evt.data?.budgetKB || '?'}KB. Top contributors: ${evt.data?.topFiles?.join(', ') || 'unknown'}`,
        autoGenerated: true,
        source: `event-bus:build`,
      })
      newLearnings++
    }

    processed.add(String(evt.ts))
  }

  if (newBreakages > 0 || newLearnings > 0) {
    writeMemory(mem)
    // Write processed markers
    ensureDir(processedFile)
    fs.writeFileSync(processedFile, [...processed].join('\n') + '\n')
    console.log(`  [event-bus] Processed: +${newBreakages} breakages, +${newLearnings} learnings`)
  } else {
    console.log(`  [event-bus] No new events to process`)
  }
}

// ── Query ──────────────────────────────────────────────────
function queryEvents(system, last) {
  let events = readEvents()
  if (system) events = events.filter(e => e.system === system)
  events = events.slice(-last)
  console.log(JSON.stringify(events, null, 2))
}

// ── Stats ──────────────────────────────────────────────────
function showStats() {
  const events = readEvents()
  const bySys = {}
  const byEvt = {}
  for (const e of events) {
    bySys[e.system] = (bySys[e.system] || 0) + 1
    byEvt[e.event] = (byEvt[e.event] || 0) + 1
  }
  console.log(`\n  Event Bus Stats`)
  console.log(`  ───────────────────────`)
  console.log(`  Total events: ${events.length}`)
  console.log(`  By system:`)
  for (const [k, v] of Object.entries(bySys).sort((a, b) => b[1] - a[1])) {
    console.log(`    ${k}: ${v}`)
  }
  console.log(`  By event:`)
  for (const [k, v] of Object.entries(byEvt).sort((a, b) => b[1] - a[1])) {
    console.log(`    ${k}: ${v}`)
  }
  console.log()
}

// ── Trim ───────────────────────────────────────────────────
function trimEvents() {
  const events = readEvents()
  const cutoff = Date.now() - MAX_AGE_DAYS * 86400000
  const kept = events.filter(e => e.ts > cutoff).slice(-MAX_EVENTS)
  const removed = events.length - kept.length
  ensureDir(EVENTS_FILE)
  fs.writeFileSync(EVENTS_FILE, kept.map(e => JSON.stringify(e)).join('\n') + (kept.length ? '\n' : ''))
  console.log(`  [event-bus] Trimmed ${removed} old events, ${kept.length} remaining`)
}

// ── CLI ────────────────────────────────────────────────────
const args = process.argv.slice(2)
const cmd = args[0] || 'stats'

switch (cmd) {
  case 'emit': {
    const system = (args.find(a => a.startsWith('--system=')) || '').split('=')[1] || 'unknown'
    const event = (args.find(a => a.startsWith('--event=')) || '').split('=')[1] || 'unknown'
    const severity = (args.find(a => a.startsWith('--severity=')) || '').split('=')[1] || 'info'
    const dataStr = (args.find(a => a.startsWith('--data=')) || '').split('=').slice(1).join('=') || '{}'
    let data = {}
    try { data = JSON.parse(dataStr) } catch { data = { raw: dataStr } }
    const record = appendEvent({ system, event, severity, data })
    if (!args.includes('--silent')) console.log(`  [event-bus] Emitted: ${system}/${event}`)
    break
  }
  case 'query': {
    const system = (args.find(a => a.startsWith('--system=')) || '').split('=')[1] || null
    const last = parseInt((args.find(a => a.startsWith('--last=')) || '--last=20').split('=')[1]) || 20
    queryEvents(system, last)
    break
  }
  case 'process':
    processEvents()
    break
  case 'stats':
    showStats()
    break
  case 'trim':
    trimEvents()
    break
  default:
    console.log('Usage: event-bus.cjs [emit|query|process|stats|trim]')
}
