#!/usr/bin/env node
/**
 * task.cjs — tiny resumable task-queue CLI for PINFORGE harness.
 * ─────────────────────────────────────────────────────────────────
 * Files: tasks/<id>.json (one per task) + tasks/INDEX.md (auto).
 * Schema: tasks/SCHEMA.md
 *
 * Commands (every mutation rewrites INDEX.md):
 *   node tools/task.cjs new "title"
 *   node tools/task.cjs list [--open|--all|--done|--blocked]
 *   node tools/task.cjs start    <id>
 *   node tools/task.cjs note     <id> "text"
 *   node tools/task.cjs evidence <id> "<hash> <link>"
 *   node tools/task.cjs check    <id> <move-n>
 *   node tools/task.cjs done     <id>
 *   node tools/task.cjs block    <id> "reason"
 *   node tools/task.cjs show     <id>
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, 'tasks');
if (!fs.existsSync(DIR)) fs.mkdirSync(DIR, { recursive: true });

function nowIso() { return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'); }
function todayId(seq) {
  const d = nowIso().slice(0, 10);
  return `T-${d}-${String(seq).padStart(3, '0')}`;
}

function listFiles() {
  return fs.readdirSync(DIR)
    .filter(f => f.startsWith('T-') && f.endsWith('.json'))
    .sort();
}

function load(id) {
  const f = path.join(DIR, id + '.json');
  if (!fs.existsSync(f)) return null;
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

function save(t) {
  t.updated = nowIso();
  const f = path.join(DIR, t.id + '.json');
  fs.writeFileSync(f, JSON.stringify(t, null, 2) + '\n');
  rewriteIndex();
}

function nextId() {
  const today = nowIso().slice(0, 10);
  const taken = listFiles()
    .map(f => f.replace('.json', ''))
    .filter(id => id.startsWith(`T-${today}`))
    .map(id => parseInt(id.slice(-3), 10))
    .filter(n => !isNaN(n));
  const seq = (taken.length ? Math.max(...taken) : 0) + 1;
  return todayId(seq);
}

function rewriteIndex() {
  const all = listFiles().map(f => {
    try { return JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')); }
    catch { return null; }
  }).filter(Boolean);
  const buckets = { in_progress: [], pending: [], blocked: [], done: [] };
  for (const t of all) (buckets[t.status] || buckets.pending).push(t);

  const lines = [];
  lines.push('# tasks/INDEX.md');
  lines.push('');
  lines.push(`_auto-generated by tools/task.cjs · ${nowIso()}_`);
  lines.push('');
  for (const status of ['in_progress', 'pending', 'blocked', 'done']) {
    if (!buckets[status].length) continue;
    lines.push(`## ${status} (${buckets[status].length})`);
    lines.push('');
    for (const t of buckets[status]) {
      const moves = t.moves || [];
      const open = moves.filter(m => !m.done).length;
      lines.push(`- **${t.id}** — ${t.title}`);
      if (moves.length) lines.push(`  · moves: ${moves.length - open}/${moves.length} done`);
      if (t.evidence && t.evidence.length) lines.push(`  · evidence: ${t.evidence.length} item(s)`);
      lines.push(`  · updated: ${t.updated}`);
    }
    lines.push('');
  }
  if (!all.length) {
    lines.push('_(empty)_');
    lines.push('');
  }
  fs.writeFileSync(path.join(DIR, 'INDEX.md'), lines.join('\n'));
}

// ─── Commands ─────────────────────────────────────────────────────
const [cmd, ...rest] = process.argv.slice(2);

function die(msg, code = 1) { console.error(msg); process.exit(code); }

function cmdNew() {
  const title = rest.join(' ').trim();
  if (!title) die('usage: task.cjs new "title"');
  const t = {
    id: nextId(),
    title,
    status: 'pending',
    created: nowIso(),
    updated: nowIso(),
    owner: process.env.USER || 'claude',
    moves: [],
    evidence: [],
    notes: '',
  };
  save(t);
  console.log(`created  ${t.id}  ${t.title}`);
}

function cmdList() {
  const filter = rest[0] || '--all';
  const all = listFiles().map(f => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')));
  const want = {
    '--all':     ['pending', 'in_progress', 'blocked', 'done'],
    '--open':    ['pending', 'in_progress'],
    '--done':    ['done'],
    '--blocked': ['blocked'],
  }[filter] || ['pending', 'in_progress', 'blocked', 'done'];
  const rows = all.filter(t => want.includes(t.status));
  if (!rows.length) { console.log('(no tasks)'); return; }
  for (const t of rows) {
    const m = t.moves || [];
    const moves = m.length ? `[${m.filter(x => x.done).length}/${m.length}]` : '[—]';
    console.log(`${t.id}  ${t.status.padEnd(11)} ${moves}  ${t.title}`);
  }
}

function mut(cmdName, fn) {
  const id = rest[0];
  if (!id) die(`usage: task.cjs ${cmdName} <id> ...`);
  const t = load(id);
  if (!t) die(`no such task: ${id}`);
  fn(t, rest.slice(1));
  save(t);
  console.log(`${cmdName.padEnd(8)} ${t.id}  status=${t.status}`);
}

function cmdStart()    { mut('start',    t => { t.status = 'in_progress'; }); }
function cmdDone()     { mut('done',     t => { t.status = 'done'; }); }
function cmdBlock()    { mut('block',    (t, a) => { t.status = 'blocked'; if (a.length) t.notes = ((t.notes||'') + (t.notes ? '\n':'') + 'BLOCK: ' + a.join(' ')); }); }
function cmdNote()     { mut('note',     (t, a) => { t.notes = ((t.notes||'') + (t.notes ? '\n':'') + a.join(' ')); }); }
function cmdEvidence() { mut('evidence', (t, a) => { t.evidence = t.evidence || []; t.evidence.push({ at: nowIso(), text: a.join(' ') }); }); }
function cmdCheck()    {
  mut('check', (t, a) => {
    const n = parseInt(a[0], 10);
    if (!t.moves) die('task has no moves[] — add via show + manual edit, or recreate');
    const m = t.moves.find(x => x.n === n);
    if (!m) die(`no move #${n}`);
    m.done = true;
  });
}

function cmdShow() {
  const id = rest[0];
  if (!id) die('usage: task.cjs show <id>');
  const t = load(id);
  if (!t) die(`no such task: ${id}`);
  console.log(JSON.stringify(t, null, 2));
}

const dispatch = {
  new: cmdNew, list: cmdList, start: cmdStart, done: cmdDone,
  block: cmdBlock, note: cmdNote, evidence: cmdEvidence,
  check: cmdCheck, show: cmdShow,
};

if (!cmd || !dispatch[cmd]) {
  console.error('commands: new | list | start | note | evidence | check | done | block | show');
  process.exit(cmd ? 1 : 0);
}
try { dispatch[cmd](); }
catch (e) { console.error('error:', e.message); process.exit(1); }
